import Foundation

/// 支持按应用内语言生成错误详情的错误类型。
protocol AppLocalizedError: Error {
    func localizedDescription(language: AppLanguage) -> String
}

enum AppStringKey: CaseIterable, Sendable {
    case languageSystem
    case languageChinese
    case languageEnglish
    case appTagline
    case sidebarTotal
    case sidebarRecent12Months
    case sidebarRecent7Days
    case sidebarRecent30Days
    case sidebarToday
    case sidebarSettings
    case dashboardOverviewNavigation
    case dashboardSessionsNavigation
    case dashboardOverviewTitle
    case dashboardOverviewSubtitle
    case dashboardSessionsTitle
    case dashboardSessionsSubtitle
    case dashboardDataSources
    case dashboardLastLocalScan
    case dashboardMetricTotalTokens
    case dashboardMetricTotalCost
    case dashboardMetricSessions
    case dashboardMetricRecords
    case dashboardTrendTitle
    case dashboardTrendSubtitle
    case dashboardTrendTokenLegend
    case dashboardModelRankTitle
    case dashboardSourceShareTitle
    case dashboardProjectUsageTitle
    case dashboardNoProjectData
    case dashboardRangeDay
    case dashboardRange7Days
    case dashboardRange30Days
    case dashboardRangeAll
    case dashboardTotalSourcesProjectsFormat
    case dashboardScanUpdating
    case dashboardScanPending
    case dashboardScanUpdatedFormat
    case dashboardJustNow
    case dashboardMinutesAgoFormat
    case dashboardHoursAgoFormat
    case dashboardUnauthorized
    case dashboardPreviousPage
    case dashboardNextPage
    case dashboardShowingSessionsFormat
    case dashboardLatestTime
    case dashboardSessionID
    case dashboardPrimaryModel
    case dashboardNoSessions
    case dashboardCopySessionIDAccessibility
    case dashboardCopyIDAccessibilityDescription
    case dashboardInput
    case dashboardOutput
    case dashboardCache
    case dashboardReasoning
    case dashboardSessionsEmptyToday
    case settingsTitle
    case settingsDescription
    case settingsAuthorizationTitle
    case settingsAuthorizeDirectory
    case settingsAuthorized
    case settingsAuthorize
    case settingsRefreshAllData
    case settingsAutoRefreshInterval
    case settingsLaunchAtLogin
    case settingsLanguage
    case autoRefreshSeconds30
    case autoRefreshMinute1
    case autoRefreshMinutes5
    case autoRefreshMinutes15
    case autoRefreshDisabled
    case totalModelUsage
    case totalEmptyModels
    case statusLoadingUsage
    case statusNeedsHomeAuthorization
    case statusTotalNoTokenData
    case statusPartialLoading
    case chartTokenUsage
    case chartCost
    case shareTool
    case shareModel
    case shareEmpty
    case shareOther
    case recentDetailsTitle
    case recentDetailsEmpty
    case recentDetailsTime
    case recentDetailsSession
    case recentDetailsTool
    case recentDetailsProject
    case recentDetailsModel
    case recentDetailsTokens
    case recentDetailsCost
    case recentDetailsRecords
    case periodNoTokenDataSuffix
    case statusMenuOpen
    case refreshNow
    case statusMenuQuit
    case mainMenuAbout
    case privacyPolicy
    case mainMenuSettings
    case mainMenuHide
    case mainMenuHideOthers
    case mainMenuShowAll
    case mainMenuWindow
    case mainMenuMinimize
    case mainMenuZoom
    case mainMenuBringAllToFront
    case refreshInProgress
    case refreshTotalAccessibility
    case refreshUsageAccessibility
    case refreshTodayAccessibility
    case refreshingTotalAccessibility
    case refreshingUsageAccessibility
    case refreshingTodayAccessibility
    case popoverMonth
    case popoverWeek
    case popoverToday
    case popoverDailyAverage
    case popoverNoTodayTokens
    case popoverLowTodayTokens
    case popoverMediumTodayTokens
    case popoverHighTodayTokens
    case popoverVeryHighTodayTokens
    case popoverExtremeTodayTokens
    case heatmapRecent22Weeks
    case chartTokenAccessibility
    case chartCostAccessibility
    case chartTokenAccessibilitySuffix
    case chartCostAccessibilitySuffix
    case statusBarTokenUnit
    case homeAccessMessage
    case authorizeAccessPrompt
    case errorCannotAccessHome
    case errorLoadFailedPrefix
    case errorOpenCodeDatabaseNotFoundFormat
    case errorOpenCodeDatabaseOpenFailedFormat
    case errorOpenCodeDatabaseQueryFailedFormat
}

enum AppStrings {
    /// Returns localized text for a stable app string key.
    static func text(_ key: AppStringKey, language: AppLanguage) -> String {
        text(key, language: language, tables: localizedTables)
    }

    static func text(
        _ key: AppStringKey,
        language: AppLanguage,
        zhHans zhHansTable: [AppStringKey: String],
        en enTable: [AppStringKey: String]
    ) -> String {
        text(key, language: language, tables: [.zhHans: zhHansTable, .en: enTable])
    }

    private static func text(
        _ key: AppStringKey,
        language: AppLanguage,
        tables: [AppLanguage: [AppStringKey: String]]
    ) -> String {
        tables[language]?[key] ?? tables[.en]?[key] ?? String(describing: key)
    }

    private static let zhHans: [AppStringKey: String] = [
        .languageSystem: "跟随系统",
        .languageChinese: "简体中文",
        .languageEnglish: "English",
        .appTagline: "本地 AI 用量监控",
        .sidebarTotal: "总计",
        .sidebarRecent12Months: "最近 12 个月",
        .sidebarRecent7Days: "最近 7 天",
        .sidebarRecent30Days: "最近 30 天",
        .sidebarToday: "本日",
        .sidebarSettings: "设置",
        .dashboardOverviewNavigation: "总览",
        .dashboardSessionsNavigation: "会话",
        .dashboardOverviewTitle: "用量总览",
        .dashboardOverviewSubtitle: "汇总 Claude Code、Codex rollout 与 opencode SQLite 的本地记录",
        .dashboardSessionsTitle: "会话",
        .dashboardSessionsSubtitle: "按最近时间倒序查看会话聚合、成本与使用记录",
        .dashboardDataSources: "数据源",
        .dashboardLastLocalScan: "上次本地扫描",
        .dashboardMetricTotalTokens: "总 Token",
        .dashboardMetricTotalCost: "总费用",
        .dashboardMetricSessions: "会话数",
        .dashboardMetricRecords: "记录数",
        .dashboardTrendTitle: "趋势",
        .dashboardTrendSubtitle: "展示 Token 消耗与费用变化",
        .dashboardTrendTokenLegend: "Token 消耗",
        .dashboardModelRankTitle: "模型消耗排行",
        .dashboardSourceShareTitle: "来源占比",
        .dashboardProjectUsageTitle: "项目消耗",
        .dashboardNoProjectData: "暂无项目数据",
        .dashboardRangeDay: "当天",
        .dashboardRange7Days: "7天",
        .dashboardRange30Days: "30天",
        .dashboardRangeAll: "全部",
        .dashboardTotalSourcesProjectsFormat: "%d 个来源，%d 个项目",
        .dashboardScanUpdating: "正在更新本地记录。不依赖任何网络 API。",
        .dashboardScanPending: "尚未完成本地扫描。不依赖任何网络 API。",
        .dashboardScanUpdatedFormat: "%@更新。不依赖任何网络 API。",
        .dashboardJustNow: "刚刚",
        .dashboardMinutesAgoFormat: "%d 分钟前",
        .dashboardHoursAgoFormat: "%d 小时前",
        .dashboardUnauthorized: "未授权",
        .dashboardPreviousPage: "上一页",
        .dashboardNextPage: "下一页",
        .dashboardShowingSessionsFormat: "显示 %@-%@ / 共 %@ 个会话",
        .dashboardLatestTime: "最近时间 ↓",
        .dashboardSessionID: "会话 ID",
        .dashboardPrimaryModel: "主模型",
        .dashboardNoSessions: "暂无会话",
        .dashboardCopySessionIDAccessibility: "复制完整会话 ID",
        .dashboardCopyIDAccessibilityDescription: "复制完整 ID",
        .dashboardInput: "输入",
        .dashboardOutput: "输出",
        .dashboardCache: "缓存",
        .dashboardReasoning: "推理",
        .dashboardSessionsEmptyToday: "当天暂无会话记录",
        .settingsTitle: "设置",
        .settingsDescription: "管理 TokenWatch 的通用访问权限和数据刷新。",
        .settingsAuthorizationTitle: "通用访问权限",
        .settingsAuthorizeDirectory: "授权访问用户目录",
        .settingsAuthorized: "已授权",
        .settingsAuthorize: "去授权",
        .settingsRefreshAllData: "刷新全部数据",
        .settingsAutoRefreshInterval: "自动刷新间隔",
        .settingsLaunchAtLogin: "开机自启动",
        .settingsLanguage: "语言",
        .autoRefreshSeconds30: "30 秒",
        .autoRefreshMinute1: "1 分钟",
        .autoRefreshMinutes5: "5 分钟",
        .autoRefreshMinutes15: "15 分钟",
        .autoRefreshDisabled: "关闭自动刷新",
        .totalModelUsage: "模型消耗",
        .totalEmptyModels: "暂无模型数据",
        .statusLoadingUsage: "正在加载用量数据...",
        .statusNeedsHomeAuthorization: "请先在设置中授权访问用户目录",
        .statusTotalNoTokenData: "总计暂无 token 数据",
        .statusPartialLoading: "部分数据仍在加载",
        .chartTokenUsage: "Token 用量",
        .chartCost: "费用",
        .shareTool: "工具占比",
        .shareModel: "模型占比",
        .shareEmpty: "暂无数据",
        .shareOther: "其他",
        .recentDetailsTitle: "最近明细",
        .recentDetailsEmpty: "当前筛选暂无会话明细",
        .recentDetailsTime: "时间",
        .recentDetailsSession: "会话",
        .recentDetailsTool: "工具",
        .recentDetailsProject: "项目",
        .recentDetailsModel: "模型",
        .recentDetailsTokens: "Token",
        .recentDetailsCost: "成本",
        .recentDetailsRecords: "记录",
        .periodNoTokenDataSuffix: "暂无 token 数据",
        .statusMenuOpen: "打开 TokenWatch",
        .refreshNow: "立即刷新",
        .statusMenuQuit: "退出 TokenWatch",
        .mainMenuAbout: "关于 TokenWatch",
        .privacyPolicy: "隐私政策",
        .mainMenuSettings: "设置...",
        .mainMenuHide: "隐藏 TokenWatch",
        .mainMenuHideOthers: "隐藏其他",
        .mainMenuShowAll: "全部显示",
        .mainMenuWindow: "窗口",
        .mainMenuMinimize: "最小化",
        .mainMenuZoom: "缩放",
        .mainMenuBringAllToFront: "全部置于前面",
        .refreshInProgress: "正在刷新",
        .refreshTotalAccessibility: "刷新总计数据",
        .refreshUsageAccessibility: "刷新用量数据",
        .refreshTodayAccessibility: "刷新本日 token 消耗",
        .refreshingTotalAccessibility: "正在刷新总计数据",
        .refreshingUsageAccessibility: "正在刷新用量数据",
        .refreshingTodayAccessibility: "正在刷新本日 token 消耗",
        .popoverMonth: "本月",
        .popoverWeek: "本周",
        .popoverToday: "今日",
        .popoverDailyAverage: "日均",
        .popoverNoTodayTokens: "本日还没有消耗 token 哦～",
        .popoverLowTodayTokens: "本日 token 消耗很克制～",
        .popoverMediumTodayTokens: "本日 token 消耗正在加速～",
        .popoverHighTodayTokens: "本日 token 消耗有点上头～",
        .popoverVeryHighTodayTokens: "本日 token 消耗火力全开～",
        .popoverExtremeTodayTokens: "本日 token 消耗爆表～",
        .heatmapRecent22Weeks: "最近 22 周",
        .chartTokenAccessibility: "最近 12 个月 token 柱状图",
        .chartCostAccessibility: "最近 12 个月费用柱状图",
        .chartTokenAccessibilitySuffix: "token 柱状图",
        .chartCostAccessibilitySuffix: "费用柱状图",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch 想访问用户目录",
        .authorizeAccessPrompt: "授权访问",
        .errorCannotAccessHome: "无法访问用户目录,请重新授权",
        .errorLoadFailedPrefix: "数据加载失败",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db 不存在: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "无法打开 opencode.db (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "查询 opencode.db 失败 (SQLite code=%d): %@",
    ]

    private static let zhHant: [AppStringKey: String] = [
        .languageSystem: "跟隨系統",
        .languageChinese: "簡體中文",
        .languageEnglish: "English",
        .appTagline: "本地 AI 用量監控",
        .sidebarTotal: "總計",
        .sidebarRecent12Months: "最近 12 個月",
        .sidebarRecent7Days: "最近 7 天",
        .sidebarRecent30Days: "最近 30 天",
        .sidebarToday: "今日",
        .sidebarSettings: "設定",
        .dashboardOverviewNavigation: "總覽",
        .dashboardSessionsNavigation: "會話",
        .dashboardOverviewTitle: "用量總覽",
        .dashboardOverviewSubtitle: "彙總 Claude Code、Codex rollout 與 opencode SQLite 的本機記錄",
        .dashboardSessionsTitle: "會話",
        .dashboardSessionsSubtitle: "依最近時間倒序查看會話彙總、成本與使用記錄",
        .dashboardDataSources: "資料來源",
        .dashboardLastLocalScan: "上次本機掃描",
        .dashboardMetricTotalTokens: "總 Token",
        .dashboardMetricTotalCost: "總費用",
        .dashboardMetricSessions: "會話數",
        .dashboardMetricRecords: "記錄數",
        .dashboardTrendTitle: "趨勢",
        .dashboardTrendSubtitle: "顯示 Token 消耗與費用變化",
        .dashboardTrendTokenLegend: "Token 消耗",
        .dashboardModelRankTitle: "模型消耗排行",
        .dashboardSourceShareTitle: "來源占比",
        .dashboardProjectUsageTitle: "專案消耗",
        .dashboardNoProjectData: "暫無專案資料",
        .dashboardRangeDay: "當天",
        .dashboardRange7Days: "7天",
        .dashboardRange30Days: "30天",
        .dashboardRangeAll: "全部",
        .dashboardTotalSourcesProjectsFormat: "%d 個來源，%d 個專案",
        .dashboardScanUpdating: "正在更新本機記錄。不依賴任何網路 API。",
        .dashboardScanPending: "尚未完成本機掃描。不依賴任何網路 API。",
        .dashboardScanUpdatedFormat: "%@更新。不依賴任何網路 API。",
        .dashboardJustNow: "剛剛",
        .dashboardMinutesAgoFormat: "%d 分鐘前",
        .dashboardHoursAgoFormat: "%d 小時前",
        .dashboardUnauthorized: "未授權",
        .dashboardPreviousPage: "上一頁",
        .dashboardNextPage: "下一頁",
        .dashboardShowingSessionsFormat: "顯示 %@-%@ / 共 %@ 個會話",
        .dashboardLatestTime: "最近時間 ↓",
        .dashboardSessionID: "會話 ID",
        .dashboardPrimaryModel: "主模型",
        .dashboardNoSessions: "暫無會話",
        .dashboardCopySessionIDAccessibility: "複製完整會話 ID",
        .dashboardCopyIDAccessibilityDescription: "複製完整 ID",
        .dashboardInput: "輸入",
        .dashboardOutput: "輸出",
        .dashboardCache: "快取",
        .dashboardReasoning: "推理",
        .dashboardSessionsEmptyToday: "當天暫無會話記錄",
        .settingsTitle: "設定",
        .settingsDescription: "管理 TokenWatch 的一般存取權限與資料重新整理。",
        .settingsAuthorizationTitle: "一般存取權限",
        .settingsAuthorizeDirectory: "授權存取使用者目錄",
        .settingsAuthorized: "已授權",
        .settingsAuthorize: "前往授權",
        .settingsRefreshAllData: "重新整理全部資料",
        .settingsAutoRefreshInterval: "自動重新整理間隔",
        .settingsLaunchAtLogin: "開機自動啟動",
        .settingsLanguage: "語言",
        .autoRefreshSeconds30: "30 秒",
        .autoRefreshMinute1: "1 分鐘",
        .autoRefreshMinutes5: "5 分鐘",
        .autoRefreshMinutes15: "15 分鐘",
        .autoRefreshDisabled: "關閉自動重新整理",
        .totalModelUsage: "模型消耗",
        .totalEmptyModels: "暫無模型資料",
        .statusLoadingUsage: "正在載入用量資料...",
        .statusNeedsHomeAuthorization: "請先在設定中授權存取使用者目錄",
        .statusTotalNoTokenData: "總計暫無 token 資料",
        .statusPartialLoading: "部分資料仍在載入",
        .chartTokenUsage: "Token 用量",
        .chartCost: "費用",
        .shareTool: "工具占比",
        .shareModel: "模型占比",
        .shareEmpty: "暫無資料",
        .shareOther: "其他",
        .recentDetailsTitle: "最近明細",
        .recentDetailsEmpty: "目前篩選暫無會話明細",
        .recentDetailsTime: "時間",
        .recentDetailsSession: "會話",
        .recentDetailsTool: "工具",
        .recentDetailsProject: "專案",
        .recentDetailsModel: "模型",
        .recentDetailsTokens: "Token",
        .recentDetailsCost: "成本",
        .recentDetailsRecords: "記錄",
        .periodNoTokenDataSuffix: "暫無 token 資料",
        .statusMenuOpen: "開啟 TokenWatch",
        .refreshNow: "立即重新整理",
        .statusMenuQuit: "結束 TokenWatch",
        .mainMenuAbout: "關於 TokenWatch",
        .privacyPolicy: "隱私權政策",
        .mainMenuSettings: "設定...",
        .mainMenuHide: "隱藏 TokenWatch",
        .mainMenuHideOthers: "隱藏其他",
        .mainMenuShowAll: "全部顯示",
        .mainMenuWindow: "視窗",
        .mainMenuMinimize: "最小化",
        .mainMenuZoom: "縮放",
        .mainMenuBringAllToFront: "全部移到最前",
        .refreshInProgress: "正在重新整理",
        .refreshTotalAccessibility: "重新整理總計資料",
        .refreshUsageAccessibility: "重新整理用量資料",
        .refreshTodayAccessibility: "重新整理今日 token 消耗",
        .refreshingTotalAccessibility: "正在重新整理總計資料",
        .refreshingUsageAccessibility: "正在重新整理用量資料",
        .refreshingTodayAccessibility: "正在重新整理今日 token 消耗",
        .popoverMonth: "本月",
        .popoverWeek: "本週",
        .popoverToday: "今日",
        .popoverDailyAverage: "日均",
        .popoverNoTodayTokens: "今日還沒有消耗 token",
        .popoverLowTodayTokens: "今日 token 消耗很克制",
        .popoverMediumTodayTokens: "今日 token 消耗正在加速",
        .popoverHighTodayTokens: "今日 token 消耗偏高",
        .popoverVeryHighTodayTokens: "今日 token 消耗火力全開",
        .popoverExtremeTodayTokens: "今日 token 消耗爆表",
        .heatmapRecent22Weeks: "最近 22 週",
        .chartTokenAccessibility: "最近 12 個月 token 長條圖",
        .chartCostAccessibility: "最近 12 個月費用長條圖",
        .chartTokenAccessibilitySuffix: "token 長條圖",
        .chartCostAccessibilitySuffix: "費用長條圖",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch 想存取使用者目錄",
        .authorizeAccessPrompt: "授權存取",
        .errorCannotAccessHome: "無法存取使用者目錄,請重新授權",
        .errorLoadFailedPrefix: "資料載入失敗",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db 不存在: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "無法開啟 opencode.db (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "查詢 opencode.db 失敗 (SQLite code=%d): %@",
    ]

    private static let ja: [AppStringKey: String] = [
        .languageSystem: "システムに従う",
        .languageChinese: "簡体字中国語",
        .languageEnglish: "英語",
        .appTagline: "ローカル AI 使用量モニター",
        .sidebarTotal: "合計",
        .sidebarRecent12Months: "過去12か月",
        .sidebarRecent7Days: "過去7日",
        .sidebarRecent30Days: "過去30日",
        .sidebarToday: "今日",
        .sidebarSettings: "設定",
        .dashboardOverviewNavigation: "概要",
        .dashboardSessionsNavigation: "セッション",
        .dashboardOverviewTitle: "使用量の概要",
        .dashboardOverviewSubtitle: "Claude Code、Codex rollout、opencode SQLite のローカル記録を集計します",
        .dashboardSessionsTitle: "セッション",
        .dashboardSessionsSubtitle: "最新順でセッション集計、コスト、使用記録を確認します",
        .dashboardDataSources: "データソース",
        .dashboardLastLocalScan: "前回のローカルスキャン",
        .dashboardMetricTotalTokens: "合計 Token",
        .dashboardMetricTotalCost: "合計コスト",
        .dashboardMetricSessions: "セッション数",
        .dashboardMetricRecords: "記録数",
        .dashboardTrendTitle: "トレンド",
        .dashboardTrendSubtitle: "Token 使用量とコストの変化を表示",
        .dashboardTrendTokenLegend: "Token 使用量",
        .dashboardModelRankTitle: "モデル使用量ランキング",
        .dashboardSourceShareTitle: "ソース比率",
        .dashboardProjectUsageTitle: "プロジェクト使用量",
        .dashboardNoProjectData: "プロジェクトデータなし",
        .dashboardRangeDay: "当日",
        .dashboardRange7Days: "7日",
        .dashboardRange30Days: "30日",
        .dashboardRangeAll: "すべて",
        .dashboardTotalSourcesProjectsFormat: "%d 件のソース、%d 件のプロジェクト",
        .dashboardScanUpdating: "ローカル記録を更新中です。ネットワーク API は使用しません。",
        .dashboardScanPending: "ローカルスキャンはまだ完了していません。ネットワーク API は使用しません。",
        .dashboardScanUpdatedFormat: "%@に更新しました。ネットワーク API は使用しません。",
        .dashboardJustNow: "たった今",
        .dashboardMinutesAgoFormat: "%d 分前",
        .dashboardHoursAgoFormat: "%d 時間前",
        .dashboardUnauthorized: "未許可",
        .dashboardPreviousPage: "前へ",
        .dashboardNextPage: "次へ",
        .dashboardShowingSessionsFormat: "%@-%@ / %@ セッションを表示",
        .dashboardLatestTime: "最新時刻 ↓",
        .dashboardSessionID: "セッション ID",
        .dashboardPrimaryModel: "主モデル",
        .dashboardNoSessions: "セッションなし",
        .dashboardCopySessionIDAccessibility: "完全なセッション ID をコピー",
        .dashboardCopyIDAccessibilityDescription: "完全な ID をコピー",
        .dashboardInput: "入力",
        .dashboardOutput: "出力",
        .dashboardCache: "キャッシュ",
        .dashboardReasoning: "推論",
        .dashboardSessionsEmptyToday: "当日のセッション記録はありません",
        .settingsTitle: "設定",
        .settingsDescription: "TokenWatch の一般アクセス権限とデータ更新を管理します。",
        .settingsAuthorizationTitle: "一般アクセス",
        .settingsAuthorizeDirectory: "ホームフォルダへのアクセスを許可",
        .settingsAuthorized: "許可済み",
        .settingsAuthorize: "許可",
        .settingsRefreshAllData: "すべてのデータを更新",
        .settingsAutoRefreshInterval: "自動更新間隔",
        .settingsLaunchAtLogin: "ログイン時に起動",
        .settingsLanguage: "言語",
        .autoRefreshSeconds30: "30秒",
        .autoRefreshMinute1: "1分",
        .autoRefreshMinutes5: "5分",
        .autoRefreshMinutes15: "15分",
        .autoRefreshDisabled: "自動更新を無効化",
        .totalModelUsage: "モデル使用量",
        .totalEmptyModels: "モデルデータなし",
        .statusLoadingUsage: "使用量データを読み込み中...",
        .statusNeedsHomeAuthorization: "先に設定でホームフォルダへのアクセスを許可してください",
        .statusTotalNoTokenData: "合計 token データなし",
        .statusPartialLoading: "一部のデータを読み込み中",
        .chartTokenUsage: "Token 使用量",
        .chartCost: "コスト",
        .shareTool: "ツール比率",
        .shareModel: "モデル比率",
        .shareEmpty: "データなし",
        .shareOther: "その他",
        .recentDetailsTitle: "最近の詳細",
        .recentDetailsEmpty: "現在の絞り込みに会話詳細はありません",
        .recentDetailsTime: "時刻",
        .recentDetailsSession: "セッション",
        .recentDetailsTool: "ツール",
        .recentDetailsProject: "プロジェクト",
        .recentDetailsModel: "モデル",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "コスト",
        .recentDetailsRecords: "記録",
        .periodNoTokenDataSuffix: "token データなし",
        .statusMenuOpen: "TokenWatch を開く",
        .refreshNow: "今すぐ更新",
        .statusMenuQuit: "TokenWatch を終了",
        .mainMenuAbout: "TokenWatch について",
        .privacyPolicy: "プライバシーポリシー",
        .mainMenuSettings: "設定...",
        .mainMenuHide: "TokenWatch を隠す",
        .mainMenuHideOthers: "ほかを隠す",
        .mainMenuShowAll: "すべてを表示",
        .mainMenuWindow: "ウインドウ",
        .mainMenuMinimize: "しまう",
        .mainMenuZoom: "拡大/縮小",
        .mainMenuBringAllToFront: "すべてを手前に移動",
        .refreshInProgress: "更新中",
        .refreshTotalAccessibility: "合計データを更新",
        .refreshUsageAccessibility: "使用量データを更新",
        .refreshTodayAccessibility: "今日の token 使用量を更新",
        .refreshingTotalAccessibility: "合計データを更新中",
        .refreshingUsageAccessibility: "使用量データを更新中",
        .refreshingTodayAccessibility: "今日の token 使用量を更新中",
        .popoverMonth: "今月",
        .popoverWeek: "今週",
        .popoverToday: "今日",
        .popoverDailyAverage: "日平均",
        .popoverNoTodayTokens: "今日の token 使用量はまだありません",
        .popoverLowTodayTokens: "今日の token 使用量は少なめです",
        .popoverMediumTodayTokens: "今日の token 使用量が増えています",
        .popoverHighTodayTokens: "今日の token 使用量は高めです",
        .popoverVeryHighTodayTokens: "今日の token 使用量はかなり高めです",
        .popoverExtremeTodayTokens: "今日の token 使用量は上限級です",
        .heatmapRecent22Weeks: "過去22週間",
        .chartTokenAccessibility: "過去12か月の token 棒グラフ",
        .chartCostAccessibility: "過去12か月のコスト棒グラフ",
        .chartTokenAccessibilitySuffix: "token 棒グラフ",
        .chartCostAccessibilitySuffix: "コスト棒グラフ",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch がホームフォルダへのアクセスを求めています",
        .authorizeAccessPrompt: "許可",
        .errorCannotAccessHome: "ホームフォルダにアクセスできません。再度許可してください",
        .errorLoadFailedPrefix: "データの読み込みに失敗しました",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db が見つかりません: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "opencode.db を開けません (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "opencode.db のクエリに失敗しました (SQLite code=%d): %@",
    ]

    private static let ko: [AppStringKey: String] = [
        .languageSystem: "시스템 설정",
        .languageChinese: "중국어 간체",
        .languageEnglish: "영어",
        .appTagline: "로컬 AI 사용량 모니터",
        .sidebarTotal: "합계",
        .sidebarRecent12Months: "최근 12개월",
        .sidebarRecent7Days: "최근 7일",
        .sidebarRecent30Days: "최근 30일",
        .sidebarToday: "오늘",
        .sidebarSettings: "설정",
        .dashboardOverviewNavigation: "개요",
        .dashboardSessionsNavigation: "세션",
        .dashboardOverviewTitle: "사용량 개요",
        .dashboardOverviewSubtitle: "Claude Code, Codex rollout, opencode SQLite의 로컬 기록을 요약합니다",
        .dashboardSessionsTitle: "세션",
        .dashboardSessionsSubtitle: "최근 시간순으로 세션 집계, 비용, 사용 기록을 확인합니다",
        .dashboardDataSources: "데이터 소스",
        .dashboardLastLocalScan: "마지막 로컬 스캔",
        .dashboardMetricTotalTokens: "총 Token",
        .dashboardMetricTotalCost: "총 비용",
        .dashboardMetricSessions: "세션 수",
        .dashboardMetricRecords: "기록 수",
        .dashboardTrendTitle: "추세",
        .dashboardTrendSubtitle: "Token 사용량과 비용 변화를 표시",
        .dashboardTrendTokenLegend: "Token 사용량",
        .dashboardModelRankTitle: "모델 사용량 순위",
        .dashboardSourceShareTitle: "소스 비율",
        .dashboardProjectUsageTitle: "프로젝트 사용량",
        .dashboardNoProjectData: "프로젝트 데이터 없음",
        .dashboardRangeDay: "당일",
        .dashboardRange7Days: "7일",
        .dashboardRange30Days: "30일",
        .dashboardRangeAll: "전체",
        .dashboardTotalSourcesProjectsFormat: "소스 %d개, 프로젝트 %d개",
        .dashboardScanUpdating: "로컬 기록을 업데이트 중입니다. 네트워크 API를 사용하지 않습니다.",
        .dashboardScanPending: "로컬 스캔이 아직 완료되지 않았습니다. 네트워크 API를 사용하지 않습니다.",
        .dashboardScanUpdatedFormat: "%@ 업데이트됨. 네트워크 API를 사용하지 않습니다.",
        .dashboardJustNow: "방금",
        .dashboardMinutesAgoFormat: "%d분 전",
        .dashboardHoursAgoFormat: "%d시간 전",
        .dashboardUnauthorized: "미허용",
        .dashboardPreviousPage: "이전",
        .dashboardNextPage: "다음",
        .dashboardShowingSessionsFormat: "%@-%@ / 총 %@개 세션 표시",
        .dashboardLatestTime: "최근 시간 ↓",
        .dashboardSessionID: "세션 ID",
        .dashboardPrimaryModel: "주 모델",
        .dashboardNoSessions: "세션 없음",
        .dashboardCopySessionIDAccessibility: "전체 세션 ID 복사",
        .dashboardCopyIDAccessibilityDescription: "전체 ID 복사",
        .dashboardInput: "입력",
        .dashboardOutput: "출력",
        .dashboardCache: "캐시",
        .dashboardReasoning: "추론",
        .dashboardSessionsEmptyToday: "오늘 세션 기록이 없습니다",
        .settingsTitle: "설정",
        .settingsDescription: "TokenWatch의 일반 접근 권한과 데이터 새로고침을 관리합니다.",
        .settingsAuthorizationTitle: "일반 접근 권한",
        .settingsAuthorizeDirectory: "홈 폴더 접근 허용",
        .settingsAuthorized: "허용됨",
        .settingsAuthorize: "허용",
        .settingsRefreshAllData: "모든 데이터 새로고침",
        .settingsAutoRefreshInterval: "자동 새로고침 간격",
        .settingsLaunchAtLogin: "로그인 시 실행",
        .settingsLanguage: "언어",
        .autoRefreshSeconds30: "30초",
        .autoRefreshMinute1: "1분",
        .autoRefreshMinutes5: "5분",
        .autoRefreshMinutes15: "15분",
        .autoRefreshDisabled: "자동 새로고침 끄기",
        .totalModelUsage: "모델 사용량",
        .totalEmptyModels: "모델 데이터 없음",
        .statusLoadingUsage: "사용량 데이터를 불러오는 중...",
        .statusNeedsHomeAuthorization: "먼저 설정에서 홈 폴더 접근을 허용하세요",
        .statusTotalNoTokenData: "합계 token 데이터 없음",
        .statusPartialLoading: "일부 데이터를 아직 불러오는 중",
        .chartTokenUsage: "Token 사용량",
        .chartCost: "비용",
        .shareTool: "도구 비율",
        .shareModel: "모델 비율",
        .shareEmpty: "데이터 없음",
        .shareOther: "기타",
        .recentDetailsTitle: "최근 상세",
        .recentDetailsEmpty: "현재 필터에 해당하는 세션 상세가 없습니다",
        .recentDetailsTime: "시간",
        .recentDetailsSession: "세션",
        .recentDetailsTool: "도구",
        .recentDetailsProject: "프로젝트",
        .recentDetailsModel: "모델",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "비용",
        .recentDetailsRecords: "기록",
        .periodNoTokenDataSuffix: "token 데이터 없음",
        .statusMenuOpen: "TokenWatch 열기",
        .refreshNow: "지금 새로고침",
        .statusMenuQuit: "TokenWatch 종료",
        .mainMenuAbout: "TokenWatch 정보",
        .privacyPolicy: "개인정보 처리방침",
        .mainMenuSettings: "설정...",
        .mainMenuHide: "TokenWatch 숨기기",
        .mainMenuHideOthers: "다른 항목 숨기기",
        .mainMenuShowAll: "모두 보기",
        .mainMenuWindow: "윈도우",
        .mainMenuMinimize: "최소화",
        .mainMenuZoom: "확대/축소",
        .mainMenuBringAllToFront: "모두 앞으로 가져오기",
        .refreshInProgress: "새로고침 중",
        .refreshTotalAccessibility: "합계 데이터 새로고침",
        .refreshUsageAccessibility: "사용량 데이터 새로고침",
        .refreshTodayAccessibility: "오늘 token 사용량 새로고침",
        .refreshingTotalAccessibility: "합계 데이터를 새로고침 중",
        .refreshingUsageAccessibility: "사용량 데이터를 새로고침 중",
        .refreshingTodayAccessibility: "오늘 token 사용량을 새로고침 중",
        .popoverMonth: "이번 달",
        .popoverWeek: "이번 주",
        .popoverToday: "오늘",
        .popoverDailyAverage: "일평균",
        .popoverNoTodayTokens: "오늘은 아직 token 사용량이 없습니다",
        .popoverLowTodayTokens: "오늘 token 사용량은 낮습니다",
        .popoverMediumTodayTokens: "오늘 token 사용량이 늘고 있습니다",
        .popoverHighTodayTokens: "오늘 token 사용량이 높습니다",
        .popoverVeryHighTodayTokens: "오늘 token 사용량이 매우 높습니다",
        .popoverExtremeTodayTokens: "오늘 token 사용량이 한계를 넘었습니다",
        .heatmapRecent22Weeks: "최근 22주",
        .chartTokenAccessibility: "최근 12개월 token 막대 차트",
        .chartCostAccessibility: "최근 12개월 비용 막대 차트",
        .chartTokenAccessibilitySuffix: "token 막대 차트",
        .chartCostAccessibilitySuffix: "비용 막대 차트",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch가 홈 폴더 접근을 요청합니다",
        .authorizeAccessPrompt: "허용",
        .errorCannotAccessHome: "홈 폴더에 접근할 수 없습니다. 다시 허용하세요",
        .errorLoadFailedPrefix: "데이터 불러오기 실패",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db를 찾을 수 없습니다: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "opencode.db를 열 수 없습니다 (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "opencode.db 쿼리 실패 (SQLite code=%d): %@",
    ]

    private static let es: [AppStringKey: String] = [
        .languageSystem: "Sistema",
        .languageChinese: "Chino simplificado",
        .languageEnglish: "Inglés",
        .appTagline: "Monitor local de uso de IA",
        .sidebarTotal: "Total",
        .sidebarRecent12Months: "Últimos 12 meses",
        .sidebarRecent7Days: "Últimos 7 días",
        .sidebarRecent30Days: "Últimos 30 días",
        .sidebarToday: "Hoy",
        .sidebarSettings: "Configuración",
        .dashboardOverviewNavigation: "Resumen",
        .dashboardSessionsNavigation: "Sesiones",
        .dashboardOverviewTitle: "Resumen de uso",
        .dashboardOverviewSubtitle: "Resume registros locales de Claude Code, Codex rollout y opencode SQLite",
        .dashboardSessionsTitle: "Sesiones",
        .dashboardSessionsSubtitle: "Consulta sesiones agregadas, costes y registros de uso en orden reciente",
        .dashboardDataSources: "Fuentes de datos",
        .dashboardLastLocalScan: "Último escaneo local",
        .dashboardMetricTotalTokens: "Tokens totales",
        .dashboardMetricTotalCost: "Coste total",
        .dashboardMetricSessions: "Sesiones",
        .dashboardMetricRecords: "Registros",
        .dashboardTrendTitle: "Tendencia",
        .dashboardTrendSubtitle: "Muestra cambios en uso de tokens y coste",
        .dashboardTrendTokenLegend: "Uso de tokens",
        .dashboardModelRankTitle: "Ranking de uso por modelo",
        .dashboardSourceShareTitle: "Participación por fuente",
        .dashboardProjectUsageTitle: "Uso por proyecto",
        .dashboardNoProjectData: "Sin datos de proyectos",
        .dashboardRangeDay: "Día",
        .dashboardRange7Days: "7 días",
        .dashboardRange30Days: "30 días",
        .dashboardRangeAll: "Todo",
        .dashboardTotalSourcesProjectsFormat: "%d fuentes, %d proyectos",
        .dashboardScanUpdating: "Actualizando registros locales. No usa ninguna API de red.",
        .dashboardScanPending: "Aún no se completó el escaneo local. No usa ninguna API de red.",
        .dashboardScanUpdatedFormat: "Actualizado %@. No usa ninguna API de red.",
        .dashboardJustNow: "Ahora mismo",
        .dashboardMinutesAgoFormat: "hace %d min",
        .dashboardHoursAgoFormat: "hace %d h",
        .dashboardUnauthorized: "No autorizado",
        .dashboardPreviousPage: "Anterior",
        .dashboardNextPage: "Siguiente",
        .dashboardShowingSessionsFormat: "Mostrando %@-%@ de %@ sesiones",
        .dashboardLatestTime: "Hora reciente ↓",
        .dashboardSessionID: "ID de sesión",
        .dashboardPrimaryModel: "Modelo principal",
        .dashboardNoSessions: "Sin sesiones",
        .dashboardCopySessionIDAccessibility: "Copiar ID de sesión completo",
        .dashboardCopyIDAccessibilityDescription: "Copiar ID completo",
        .dashboardInput: "Entrada",
        .dashboardOutput: "Salida",
        .dashboardCache: "Caché",
        .dashboardReasoning: "Razonamiento",
        .dashboardSessionsEmptyToday: "No hay registros de sesiones hoy",
        .settingsTitle: "Configuración",
        .settingsDescription: "Gestiona los permisos de acceso generales y la actualización de datos de TokenWatch.",
        .settingsAuthorizationTitle: "Acceso general",
        .settingsAuthorizeDirectory: "Autorizar carpeta de inicio",
        .settingsAuthorized: "Autorizado",
        .settingsAuthorize: "Autorizar",
        .settingsRefreshAllData: "Actualizar todos los datos",
        .settingsAutoRefreshInterval: "Intervalo de actualización automática",
        .settingsLaunchAtLogin: "Iniciar al iniciar sesión",
        .settingsLanguage: "Idioma",
        .autoRefreshSeconds30: "30 segundos",
        .autoRefreshMinute1: "1 minuto",
        .autoRefreshMinutes5: "5 minutos",
        .autoRefreshMinutes15: "15 minutos",
        .autoRefreshDisabled: "Desactivar actualización automática",
        .totalModelUsage: "Uso por modelo",
        .totalEmptyModels: "Sin datos de modelos",
        .statusLoadingUsage: "Cargando datos de uso...",
        .statusNeedsHomeAuthorization: "Autoriza primero el acceso a la carpeta de inicio en Configuración",
        .statusTotalNoTokenData: "Sin datos totales de tokens",
        .statusPartialLoading: "Algunos datos aún se están cargando",
        .chartTokenUsage: "Uso de tokens",
        .chartCost: "Coste",
        .shareTool: "Uso por herramienta",
        .shareModel: "Uso por modelo",
        .shareEmpty: "Sin datos",
        .shareOther: "Otros",
        .recentDetailsTitle: "Detalles recientes",
        .recentDetailsEmpty: "No hay detalles de sesiones para el filtro actual",
        .recentDetailsTime: "Hora",
        .recentDetailsSession: "Sesión",
        .recentDetailsTool: "Herramienta",
        .recentDetailsProject: "Proyecto",
        .recentDetailsModel: "Modelo",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "Coste",
        .recentDetailsRecords: "Registros",
        .periodNoTokenDataSuffix: "no tiene datos de tokens",
        .statusMenuOpen: "Abrir TokenWatch",
        .refreshNow: "Actualizar ahora",
        .statusMenuQuit: "Salir de TokenWatch",
        .mainMenuAbout: "Acerca de TokenWatch",
        .privacyPolicy: "Política de privacidad",
        .mainMenuSettings: "Configuración...",
        .mainMenuHide: "Ocultar TokenWatch",
        .mainMenuHideOthers: "Ocultar otros",
        .mainMenuShowAll: "Mostrar todo",
        .mainMenuWindow: "Ventana",
        .mainMenuMinimize: "Minimizar",
        .mainMenuZoom: "Zoom",
        .mainMenuBringAllToFront: "Traer todo al frente",
        .refreshInProgress: "Actualizando",
        .refreshTotalAccessibility: "Actualizar datos totales",
        .refreshUsageAccessibility: "Actualizar datos de uso",
        .refreshTodayAccessibility: "Actualizar uso de tokens de hoy",
        .refreshingTotalAccessibility: "Actualizando datos totales",
        .refreshingUsageAccessibility: "Actualizando datos de uso",
        .refreshingTodayAccessibility: "Actualizando uso de tokens de hoy",
        .popoverMonth: "Mes",
        .popoverWeek: "Semana",
        .popoverToday: "Hoy",
        .popoverDailyAverage: "Prom. diario",
        .popoverNoTodayTokens: "Hoy no hay uso de tokens",
        .popoverLowTodayTokens: "El uso de tokens de hoy es bajo",
        .popoverMediumTodayTokens: "El uso de tokens de hoy está aumentando",
        .popoverHighTodayTokens: "El uso de tokens de hoy es alto",
        .popoverVeryHighTodayTokens: "El uso de tokens de hoy está muy alto",
        .popoverExtremeTodayTokens: "El uso de tokens de hoy está fuera de escala",
        .heatmapRecent22Weeks: "Últimas 22 semanas",
        .chartTokenAccessibility: "Gráfico de barras de tokens de los últimos 12 meses",
        .chartCostAccessibility: "Gráfico de barras de coste de los últimos 12 meses",
        .chartTokenAccessibilitySuffix: "gráfico de barras de tokens",
        .chartCostAccessibilitySuffix: "gráfico de barras de coste",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch quiere acceder a tu carpeta de inicio",
        .authorizeAccessPrompt: "Autorizar",
        .errorCannotAccessHome: "No se puede acceder a la carpeta de inicio. Autoriza de nuevo",
        .errorLoadFailedPrefix: "Error al cargar datos",
        .errorOpenCodeDatabaseNotFoundFormat: "No se encontró opencode.db: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "No se pudo abrir opencode.db (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "Error al consultar opencode.db (SQLite code=%d): %@",
    ]

    private static let de: [AppStringKey: String] = [
        .languageSystem: "System",
        .languageChinese: "Vereinfachtes Chinesisch",
        .languageEnglish: "Englisch",
        .appTagline: "Lokaler KI-Nutzungsmonitor",
        .sidebarTotal: "Gesamt",
        .sidebarRecent12Months: "Letzte 12 Monate",
        .sidebarRecent7Days: "Letzte 7 Tage",
        .sidebarRecent30Days: "Letzte 30 Tage",
        .sidebarToday: "Heute",
        .sidebarSettings: "Einstellungen",
        .dashboardOverviewNavigation: "Übersicht",
        .dashboardSessionsNavigation: "Sitzungen",
        .dashboardOverviewTitle: "Nutzungsübersicht",
        .dashboardOverviewSubtitle: "Fasst lokale Einträge aus Claude Code, Codex rollout und opencode SQLite zusammen",
        .dashboardSessionsTitle: "Sitzungen",
        .dashboardSessionsSubtitle: "Sitzungsaggregate, Kosten und Nutzungsdaten nach letzter Aktivität anzeigen",
        .dashboardDataSources: "Datenquellen",
        .dashboardLastLocalScan: "Letzter lokaler Scan",
        .dashboardMetricTotalTokens: "Gesamt-Tokens",
        .dashboardMetricTotalCost: "Gesamtkosten",
        .dashboardMetricSessions: "Sitzungen",
        .dashboardMetricRecords: "Einträge",
        .dashboardTrendTitle: "Trend",
        .dashboardTrendSubtitle: "Zeigt Änderungen bei Token-Nutzung und Kosten",
        .dashboardTrendTokenLegend: "Token-Nutzung",
        .dashboardModelRankTitle: "Modellnutzung Ranking",
        .dashboardSourceShareTitle: "Quellenanteil",
        .dashboardProjectUsageTitle: "Projektnutzung",
        .dashboardNoProjectData: "Keine Projektdaten",
        .dashboardRangeDay: "Tag",
        .dashboardRange7Days: "7 Tage",
        .dashboardRange30Days: "30 Tage",
        .dashboardRangeAll: "Alle",
        .dashboardTotalSourcesProjectsFormat: "%d Quellen, %d Projekte",
        .dashboardScanUpdating: "Lokale Einträge werden aktualisiert. Es wird keine Netzwerk-API verwendet.",
        .dashboardScanPending: "Der lokale Scan ist noch nicht abgeschlossen. Es wird keine Netzwerk-API verwendet.",
        .dashboardScanUpdatedFormat: "Vor %@ aktualisiert. Es wird keine Netzwerk-API verwendet.",
        .dashboardJustNow: "Gerade eben",
        .dashboardMinutesAgoFormat: "vor %d Min.",
        .dashboardHoursAgoFormat: "vor %d Std.",
        .dashboardUnauthorized: "Nicht autorisiert",
        .dashboardPreviousPage: "Zurück",
        .dashboardNextPage: "Weiter",
        .dashboardShowingSessionsFormat: "%@-%@ von %@ Sitzungen",
        .dashboardLatestTime: "Letzte Zeit ↓",
        .dashboardSessionID: "Sitzungs-ID",
        .dashboardPrimaryModel: "Hauptmodell",
        .dashboardNoSessions: "Keine Sitzungen",
        .dashboardCopySessionIDAccessibility: "Vollständige Sitzungs-ID kopieren",
        .dashboardCopyIDAccessibilityDescription: "Vollständige ID kopieren",
        .dashboardInput: "Eingabe",
        .dashboardOutput: "Ausgabe",
        .dashboardCache: "Cache",
        .dashboardReasoning: "Reasoning",
        .dashboardSessionsEmptyToday: "Heute keine Sitzungsaufzeichnungen",
        .settingsTitle: "Einstellungen",
        .settingsDescription: "Verwalte allgemeine Zugriffsrechte und Datenaktualisierung für TokenWatch.",
        .settingsAuthorizationTitle: "Allgemeiner Zugriff",
        .settingsAuthorizeDirectory: "Home-Ordner autorisieren",
        .settingsAuthorized: "Autorisiert",
        .settingsAuthorize: "Autorisieren",
        .settingsRefreshAllData: "Alle Daten aktualisieren",
        .settingsAutoRefreshInterval: "Intervall für Auto-Aktualisierung",
        .settingsLaunchAtLogin: "Beim Anmelden starten",
        .settingsLanguage: "Sprache",
        .autoRefreshSeconds30: "30 Sekunden",
        .autoRefreshMinute1: "1 Minute",
        .autoRefreshMinutes5: "5 Minuten",
        .autoRefreshMinutes15: "15 Minuten",
        .autoRefreshDisabled: "Auto-Aktualisierung deaktivieren",
        .totalModelUsage: "Modellnutzung",
        .totalEmptyModels: "Keine Modelldaten",
        .statusLoadingUsage: "Nutzungsdaten werden geladen...",
        .statusNeedsHomeAuthorization: "Autorisiere zuerst den Home-Ordnerzugriff in den Einstellungen",
        .statusTotalNoTokenData: "Keine gesamten Token-Daten",
        .statusPartialLoading: "Einige Daten werden noch geladen",
        .chartTokenUsage: "Token-Nutzung",
        .chartCost: "Kosten",
        .shareTool: "Tool-Anteil",
        .shareModel: "Modell-Anteil",
        .shareEmpty: "Keine Daten",
        .shareOther: "Andere",
        .recentDetailsTitle: "Aktuelle Details",
        .recentDetailsEmpty: "Keine Sitzungsdetails für den aktuellen Filter",
        .recentDetailsTime: "Zeit",
        .recentDetailsSession: "Sitzung",
        .recentDetailsTool: "Tool",
        .recentDetailsProject: "Projekt",
        .recentDetailsModel: "Modell",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "Kosten",
        .recentDetailsRecords: "Einträge",
        .periodNoTokenDataSuffix: "hat keine Token-Daten",
        .statusMenuOpen: "TokenWatch öffnen",
        .refreshNow: "Jetzt aktualisieren",
        .statusMenuQuit: "TokenWatch beenden",
        .mainMenuAbout: "Über TokenWatch",
        .privacyPolicy: "Datenschutzrichtlinie",
        .mainMenuSettings: "Einstellungen...",
        .mainMenuHide: "TokenWatch ausblenden",
        .mainMenuHideOthers: "Andere ausblenden",
        .mainMenuShowAll: "Alle einblenden",
        .mainMenuWindow: "Fenster",
        .mainMenuMinimize: "Minimieren",
        .mainMenuZoom: "Zoomen",
        .mainMenuBringAllToFront: "Alle nach vorne",
        .refreshInProgress: "Aktualisierung läuft",
        .refreshTotalAccessibility: "Gesamtdaten aktualisieren",
        .refreshUsageAccessibility: "Nutzungsdaten aktualisieren",
        .refreshTodayAccessibility: "Heutige Token-Nutzung aktualisieren",
        .refreshingTotalAccessibility: "Gesamtdaten werden aktualisiert",
        .refreshingUsageAccessibility: "Nutzungsdaten werden aktualisiert",
        .refreshingTodayAccessibility: "Heutige Token-Nutzung wird aktualisiert",
        .popoverMonth: "Monat",
        .popoverWeek: "Woche",
        .popoverToday: "Heute",
        .popoverDailyAverage: "Tagesdurchschnitt",
        .popoverNoTodayTokens: "Heute keine Token-Nutzung",
        .popoverLowTodayTokens: "Die heutige Token-Nutzung ist niedrig",
        .popoverMediumTodayTokens: "Die heutige Token-Nutzung nimmt zu",
        .popoverHighTodayTokens: "Die heutige Token-Nutzung ist hoch",
        .popoverVeryHighTodayTokens: "Die heutige Token-Nutzung ist sehr hoch",
        .popoverExtremeTodayTokens: "Die heutige Token-Nutzung ist am Anschlag",
        .heatmapRecent22Weeks: "Letzte 22 Wochen",
        .chartTokenAccessibility: "Token-Balkendiagramm der letzten 12 Monate",
        .chartCostAccessibility: "Kosten-Balkendiagramm der letzten 12 Monate",
        .chartTokenAccessibilitySuffix: "Token-Balkendiagramm",
        .chartCostAccessibilitySuffix: "Kosten-Balkendiagramm",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch möchte auf deinen Home-Ordner zugreifen",
        .authorizeAccessPrompt: "Autorisieren",
        .errorCannotAccessHome: "Home-Ordner kann nicht geöffnet werden. Bitte erneut autorisieren",
        .errorLoadFailedPrefix: "Daten konnten nicht geladen werden",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db wurde nicht gefunden: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "opencode.db konnte nicht geöffnet werden (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "Abfrage von opencode.db fehlgeschlagen (SQLite code=%d): %@",
    ]

    private static let fr: [AppStringKey: String] = [
        .languageSystem: "Système",
        .languageChinese: "Chinois simplifié",
        .languageEnglish: "Anglais",
        .appTagline: "Suivi local de l'utilisation IA",
        .sidebarTotal: "Total",
        .sidebarRecent12Months: "12 derniers mois",
        .sidebarRecent7Days: "7 derniers jours",
        .sidebarRecent30Days: "30 derniers jours",
        .sidebarToday: "Aujourd'hui",
        .sidebarSettings: "Paramètres",
        .dashboardOverviewNavigation: "Vue d'ensemble",
        .dashboardSessionsNavigation: "Sessions",
        .dashboardOverviewTitle: "Vue d'ensemble de l'utilisation",
        .dashboardOverviewSubtitle: "Résume les enregistrements locaux de Claude Code, Codex rollout et opencode SQLite",
        .dashboardSessionsTitle: "Sessions",
        .dashboardSessionsSubtitle: "Consultez les agrégats de sessions, les coûts et les enregistrements par activité récente",
        .dashboardDataSources: "Sources de données",
        .dashboardLastLocalScan: "Dernier scan local",
        .dashboardMetricTotalTokens: "Tokens totaux",
        .dashboardMetricTotalCost: "Coût total",
        .dashboardMetricSessions: "Sessions",
        .dashboardMetricRecords: "Enregistrements",
        .dashboardTrendTitle: "Tendance",
        .dashboardTrendSubtitle: "Affiche l'évolution des tokens et des coûts",
        .dashboardTrendTokenLegend: "Utilisation des tokens",
        .dashboardModelRankTitle: "Classement d'utilisation des modèles",
        .dashboardSourceShareTitle: "Part par source",
        .dashboardProjectUsageTitle: "Utilisation par projet",
        .dashboardNoProjectData: "Aucune donnée de projet",
        .dashboardRangeDay: "Jour",
        .dashboardRange7Days: "7 jours",
        .dashboardRange30Days: "30 jours",
        .dashboardRangeAll: "Tout",
        .dashboardTotalSourcesProjectsFormat: "%d sources, %d projets",
        .dashboardScanUpdating: "Mise à jour des enregistrements locaux. Aucune API réseau n'est utilisée.",
        .dashboardScanPending: "Le scan local n'est pas encore terminé. Aucune API réseau n'est utilisée.",
        .dashboardScanUpdatedFormat: "Mis à jour %@. Aucune API réseau n'est utilisée.",
        .dashboardJustNow: "À l'instant",
        .dashboardMinutesAgoFormat: "il y a %d min",
        .dashboardHoursAgoFormat: "il y a %d h",
        .dashboardUnauthorized: "Non autorisé",
        .dashboardPreviousPage: "Précédent",
        .dashboardNextPage: "Suivant",
        .dashboardShowingSessionsFormat: "Affichage %@-%@ sur %@ sessions",
        .dashboardLatestTime: "Dernière activité ↓",
        .dashboardSessionID: "ID de session",
        .dashboardPrimaryModel: "Modèle principal",
        .dashboardNoSessions: "Aucune session",
        .dashboardCopySessionIDAccessibility: "Copier l'ID de session complet",
        .dashboardCopyIDAccessibilityDescription: "Copier l'ID complet",
        .dashboardInput: "Entrée",
        .dashboardOutput: "Sortie",
        .dashboardCache: "Cache",
        .dashboardReasoning: "Raisonnement",
        .dashboardSessionsEmptyToday: "Aucun enregistrement de session aujourd'hui",
        .settingsTitle: "Paramètres",
        .settingsDescription: "Gérez les autorisations d'accès générales et l'actualisation des données de TokenWatch.",
        .settingsAuthorizationTitle: "Accès général",
        .settingsAuthorizeDirectory: "Autoriser le dossier personnel",
        .settingsAuthorized: "Autorisé",
        .settingsAuthorize: "Autoriser",
        .settingsRefreshAllData: "Actualiser toutes les données",
        .settingsAutoRefreshInterval: "Intervalle d'actualisation auto",
        .settingsLaunchAtLogin: "Lancer à l’ouverture de session",
        .settingsLanguage: "Langue",
        .autoRefreshSeconds30: "30 secondes",
        .autoRefreshMinute1: "1 minute",
        .autoRefreshMinutes5: "5 minutes",
        .autoRefreshMinutes15: "15 minutes",
        .autoRefreshDisabled: "Désactiver l'actualisation auto",
        .totalModelUsage: "Utilisation par modèle",
        .totalEmptyModels: "Aucune donnée de modèle",
        .statusLoadingUsage: "Chargement des données d'utilisation...",
        .statusNeedsHomeAuthorization: "Autorisez d'abord l'accès au dossier personnel dans Paramètres",
        .statusTotalNoTokenData: "Aucune donnée totale de tokens",
        .statusPartialLoading: "Certaines données sont encore en cours de chargement",
        .chartTokenUsage: "Utilisation des tokens",
        .chartCost: "Coût",
        .shareTool: "Part par outil",
        .shareModel: "Part par modèle",
        .shareEmpty: "Aucune donnée",
        .shareOther: "Autres",
        .recentDetailsTitle: "Détails récents",
        .recentDetailsEmpty: "Aucun détail de session pour le filtre actuel",
        .recentDetailsTime: "Heure",
        .recentDetailsSession: "Session",
        .recentDetailsTool: "Outil",
        .recentDetailsProject: "Projet",
        .recentDetailsModel: "Modèle",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "Coût",
        .recentDetailsRecords: "Enregistrements",
        .periodNoTokenDataSuffix: "n'a aucune donnée de tokens",
        .statusMenuOpen: "Ouvrir TokenWatch",
        .refreshNow: "Actualiser maintenant",
        .statusMenuQuit: "Quitter TokenWatch",
        .mainMenuAbout: "À propos de TokenWatch",
        .privacyPolicy: "Politique de confidentialité",
        .mainMenuSettings: "Paramètres...",
        .mainMenuHide: "Masquer TokenWatch",
        .mainMenuHideOthers: "Masquer les autres",
        .mainMenuShowAll: "Tout afficher",
        .mainMenuWindow: "Fenêtre",
        .mainMenuMinimize: "Réduire",
        .mainMenuZoom: "Zoom",
        .mainMenuBringAllToFront: "Tout ramener au premier plan",
        .refreshInProgress: "Actualisation",
        .refreshTotalAccessibility: "Actualiser les données totales",
        .refreshUsageAccessibility: "Actualiser les données d'utilisation",
        .refreshTodayAccessibility: "Actualiser l'utilisation des tokens d'aujourd'hui",
        .refreshingTotalAccessibility: "Actualisation des données totales",
        .refreshingUsageAccessibility: "Actualisation des données d'utilisation",
        .refreshingTodayAccessibility: "Actualisation de l'utilisation des tokens d'aujourd'hui",
        .popoverMonth: "Mois",
        .popoverWeek: "Semaine",
        .popoverToday: "Aujourd'hui",
        .popoverDailyAverage: "Moy. jour",
        .popoverNoTodayTokens: "Aucune utilisation de tokens aujourd'hui",
        .popoverLowTodayTokens: "L'utilisation des tokens d'aujourd'hui est faible",
        .popoverMediumTodayTokens: "L'utilisation des tokens d'aujourd'hui accélère",
        .popoverHighTodayTokens: "L'utilisation des tokens d'aujourd'hui est élevée",
        .popoverVeryHighTodayTokens: "L'utilisation des tokens d'aujourd'hui est très élevée",
        .popoverExtremeTodayTokens: "L'utilisation des tokens d'aujourd'hui explose",
        .heatmapRecent22Weeks: "22 dernières semaines",
        .chartTokenAccessibility: "Graphique à barres des tokens des 12 derniers mois",
        .chartCostAccessibility: "Graphique à barres des coûts des 12 derniers mois",
        .chartTokenAccessibilitySuffix: "graphique à barres des tokens",
        .chartCostAccessibilitySuffix: "graphique à barres des coûts",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch veut accéder à votre dossier personnel",
        .authorizeAccessPrompt: "Autoriser",
        .errorCannotAccessHome: "Impossible d'accéder au dossier personnel. Veuillez autoriser à nouveau",
        .errorLoadFailedPrefix: "Échec du chargement des données",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db introuvable : %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "Impossible d'ouvrir opencode.db (SQLite code=%d) : %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "Échec de la requête opencode.db (SQLite code=%d) : %@",
    ]

    private static let ptBR: [AppStringKey: String] = [
        .languageSystem: "Sistema",
        .languageChinese: "Chinês simplificado",
        .languageEnglish: "Inglês",
        .appTagline: "Monitor local de uso de IA",
        .sidebarTotal: "Total",
        .sidebarRecent12Months: "Últimos 12 meses",
        .sidebarRecent7Days: "Últimos 7 dias",
        .sidebarRecent30Days: "Últimos 30 dias",
        .sidebarToday: "Hoje",
        .sidebarSettings: "Configurações",
        .dashboardOverviewNavigation: "Visão geral",
        .dashboardSessionsNavigation: "Sessões",
        .dashboardOverviewTitle: "Visão geral de uso",
        .dashboardOverviewSubtitle: "Resume registros locais de Claude Code, Codex rollout e opencode SQLite",
        .dashboardSessionsTitle: "Sessões",
        .dashboardSessionsSubtitle: "Veja sessões agregadas, custos e registros por atividade recente",
        .dashboardDataSources: "Fontes de dados",
        .dashboardLastLocalScan: "Última varredura local",
        .dashboardMetricTotalTokens: "Tokens totais",
        .dashboardMetricTotalCost: "Custo total",
        .dashboardMetricSessions: "Sessões",
        .dashboardMetricRecords: "Registros",
        .dashboardTrendTitle: "Tendência",
        .dashboardTrendSubtitle: "Mostra mudanças de uso de tokens e custo",
        .dashboardTrendTokenLegend: "Uso de tokens",
        .dashboardModelRankTitle: "Ranking de uso por modelo",
        .dashboardSourceShareTitle: "Participação por fonte",
        .dashboardProjectUsageTitle: "Uso por projeto",
        .dashboardNoProjectData: "Sem dados de projetos",
        .dashboardRangeDay: "Dia",
        .dashboardRange7Days: "7 dias",
        .dashboardRange30Days: "30 dias",
        .dashboardRangeAll: "Tudo",
        .dashboardTotalSourcesProjectsFormat: "%d fontes, %d projetos",
        .dashboardScanUpdating: "Atualizando registros locais. Não usa nenhuma API de rede.",
        .dashboardScanPending: "A varredura local ainda não terminou. Não usa nenhuma API de rede.",
        .dashboardScanUpdatedFormat: "Atualizado %@. Não usa nenhuma API de rede.",
        .dashboardJustNow: "Agora mesmo",
        .dashboardMinutesAgoFormat: "há %d min",
        .dashboardHoursAgoFormat: "há %d h",
        .dashboardUnauthorized: "Não autorizado",
        .dashboardPreviousPage: "Anterior",
        .dashboardNextPage: "Próxima",
        .dashboardShowingSessionsFormat: "Mostrando %@-%@ de %@ sessões",
        .dashboardLatestTime: "Atividade recente ↓",
        .dashboardSessionID: "ID da sessão",
        .dashboardPrimaryModel: "Modelo principal",
        .dashboardNoSessions: "Sem sessões",
        .dashboardCopySessionIDAccessibility: "Copiar ID completo da sessão",
        .dashboardCopyIDAccessibilityDescription: "Copiar ID completo",
        .dashboardInput: "Entrada",
        .dashboardOutput: "Saída",
        .dashboardCache: "Cache",
        .dashboardReasoning: "Raciocínio",
        .dashboardSessionsEmptyToday: "Sem registros de sessão hoje",
        .settingsTitle: "Configurações",
        .settingsDescription: "Gerencie permissões gerais de acesso e atualização de dados do TokenWatch.",
        .settingsAuthorizationTitle: "Acesso geral",
        .settingsAuthorizeDirectory: "Autorizar pasta inicial",
        .settingsAuthorized: "Autorizado",
        .settingsAuthorize: "Autorizar",
        .settingsRefreshAllData: "Atualizar todos os dados",
        .settingsAutoRefreshInterval: "Intervalo de atualização automática",
        .settingsLaunchAtLogin: "Iniciar ao entrar",
        .settingsLanguage: "Idioma",
        .autoRefreshSeconds30: "30 segundos",
        .autoRefreshMinute1: "1 minuto",
        .autoRefreshMinutes5: "5 minutos",
        .autoRefreshMinutes15: "15 minutos",
        .autoRefreshDisabled: "Desativar atualização automática",
        .totalModelUsage: "Uso por modelo",
        .totalEmptyModels: "Sem dados de modelos",
        .statusLoadingUsage: "Carregando dados de uso...",
        .statusNeedsHomeAuthorization: "Autorize primeiro o acesso à pasta inicial em Configurações",
        .statusTotalNoTokenData: "Sem dados totais de tokens",
        .statusPartialLoading: "Alguns dados ainda estão carregando",
        .chartTokenUsage: "Uso de tokens",
        .chartCost: "Custo",
        .shareTool: "Participação por ferramenta",
        .shareModel: "Participação por modelo",
        .shareEmpty: "Sem dados",
        .shareOther: "Outros",
        .recentDetailsTitle: "Detalhes recentes",
        .recentDetailsEmpty: "Sem detalhes de sessões para o filtro atual",
        .recentDetailsTime: "Hora",
        .recentDetailsSession: "Sessão",
        .recentDetailsTool: "Ferramenta",
        .recentDetailsProject: "Projeto",
        .recentDetailsModel: "Modelo",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "Custo",
        .recentDetailsRecords: "Registros",
        .periodNoTokenDataSuffix: "não tem dados de tokens",
        .statusMenuOpen: "Abrir TokenWatch",
        .refreshNow: "Atualizar agora",
        .statusMenuQuit: "Sair do TokenWatch",
        .mainMenuAbout: "Sobre o TokenWatch",
        .privacyPolicy: "Política de Privacidade",
        .mainMenuSettings: "Configurações...",
        .mainMenuHide: "Ocultar TokenWatch",
        .mainMenuHideOthers: "Ocultar Outros",
        .mainMenuShowAll: "Mostrar Tudo",
        .mainMenuWindow: "Janela",
        .mainMenuMinimize: "Minimizar",
        .mainMenuZoom: "Zoom",
        .mainMenuBringAllToFront: "Trazer Tudo para Frente",
        .refreshInProgress: "Atualizando",
        .refreshTotalAccessibility: "Atualizar dados totais",
        .refreshUsageAccessibility: "Atualizar dados de uso",
        .refreshTodayAccessibility: "Atualizar uso de tokens de hoje",
        .refreshingTotalAccessibility: "Atualizando dados totais",
        .refreshingUsageAccessibility: "Atualizando dados de uso",
        .refreshingTodayAccessibility: "Atualizando uso de tokens de hoje",
        .popoverMonth: "Mês",
        .popoverWeek: "Semana",
        .popoverToday: "Hoje",
        .popoverDailyAverage: "Média diária",
        .popoverNoTodayTokens: "Sem uso de tokens hoje",
        .popoverLowTodayTokens: "O uso de tokens de hoje está leve",
        .popoverMediumTodayTokens: "O uso de tokens de hoje está aumentando",
        .popoverHighTodayTokens: "O uso de tokens de hoje está alto",
        .popoverVeryHighTodayTokens: "O uso de tokens de hoje está muito alto",
        .popoverExtremeTodayTokens: "O uso de tokens de hoje passou do limite",
        .heatmapRecent22Weeks: "Últimas 22 semanas",
        .chartTokenAccessibility: "Gráfico de barras de tokens dos últimos 12 meses",
        .chartCostAccessibility: "Gráfico de barras de custos dos últimos 12 meses",
        .chartTokenAccessibilitySuffix: "gráfico de barras de tokens",
        .chartCostAccessibilitySuffix: "gráfico de barras de custos",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch quer acessar sua pasta inicial",
        .authorizeAccessPrompt: "Autorizar",
        .errorCannotAccessHome: "Não foi possível acessar a pasta inicial. Autorize novamente",
        .errorLoadFailedPrefix: "Falha ao carregar dados",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db não encontrado: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "Não foi possível abrir opencode.db (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "Falha ao consultar opencode.db (SQLite code=%d): %@",
    ]

    private static let it: [AppStringKey: String] = [
        .languageSystem: "Sistema",
        .languageChinese: "Cinese semplificato",
        .languageEnglish: "Inglese",
        .appTagline: "Monitor locale dell'uso IA",
        .sidebarTotal: "Totale",
        .sidebarRecent12Months: "Ultimi 12 mesi",
        .sidebarRecent7Days: "Ultimi 7 giorni",
        .sidebarRecent30Days: "Ultimi 30 giorni",
        .sidebarToday: "Oggi",
        .sidebarSettings: "Impostazioni",
        .dashboardOverviewNavigation: "Panoramica",
        .dashboardSessionsNavigation: "Sessioni",
        .dashboardOverviewTitle: "Panoramica utilizzo",
        .dashboardOverviewSubtitle: "Riepiloga i record locali di Claude Code, Codex rollout e opencode SQLite",
        .dashboardSessionsTitle: "Sessioni",
        .dashboardSessionsSubtitle: "Visualizza sessioni aggregate, costi e record per attività recente",
        .dashboardDataSources: "Origini dati",
        .dashboardLastLocalScan: "Ultima scansione locale",
        .dashboardMetricTotalTokens: "Token totali",
        .dashboardMetricTotalCost: "Costo totale",
        .dashboardMetricSessions: "Sessioni",
        .dashboardMetricRecords: "Record",
        .dashboardTrendTitle: "Tendenza",
        .dashboardTrendSubtitle: "Mostra le variazioni di utilizzo token e costo",
        .dashboardTrendTokenLegend: "Utilizzo token",
        .dashboardModelRankTitle: "Classifica utilizzo modelli",
        .dashboardSourceShareTitle: "Quota per origine",
        .dashboardProjectUsageTitle: "Utilizzo progetto",
        .dashboardNoProjectData: "Nessun dato progetto",
        .dashboardRangeDay: "Giorno",
        .dashboardRange7Days: "7 giorni",
        .dashboardRange30Days: "30 giorni",
        .dashboardRangeAll: "Tutto",
        .dashboardTotalSourcesProjectsFormat: "%d origini, %d progetti",
        .dashboardScanUpdating: "Aggiornamento dei record locali. Non usa API di rete.",
        .dashboardScanPending: "La scansione locale non è ancora completata. Non usa API di rete.",
        .dashboardScanUpdatedFormat: "Aggiornato %@. Non usa API di rete.",
        .dashboardJustNow: "Ora",
        .dashboardMinutesAgoFormat: "%d min fa",
        .dashboardHoursAgoFormat: "%d h fa",
        .dashboardUnauthorized: "Non autorizzato",
        .dashboardPreviousPage: "Precedente",
        .dashboardNextPage: "Successiva",
        .dashboardShowingSessionsFormat: "Mostra %@-%@ di %@ sessioni",
        .dashboardLatestTime: "Attività recente ↓",
        .dashboardSessionID: "ID sessione",
        .dashboardPrimaryModel: "Modello principale",
        .dashboardNoSessions: "Nessuna sessione",
        .dashboardCopySessionIDAccessibility: "Copia ID sessione completo",
        .dashboardCopyIDAccessibilityDescription: "Copia ID completo",
        .dashboardInput: "Input",
        .dashboardOutput: "Output",
        .dashboardCache: "Cache",
        .dashboardReasoning: "Ragionamento",
        .dashboardSessionsEmptyToday: "Nessun record di sessione oggi",
        .settingsTitle: "Impostazioni",
        .settingsDescription: "Gestisci le autorizzazioni generali di accesso e l'aggiornamento dei dati di TokenWatch.",
        .settingsAuthorizationTitle: "Accesso generale",
        .settingsAuthorizeDirectory: "Autorizza cartella home",
        .settingsAuthorized: "Autorizzato",
        .settingsAuthorize: "Autorizza",
        .settingsRefreshAllData: "Aggiorna tutti i dati",
        .settingsAutoRefreshInterval: "Intervallo di aggiornamento automatico",
        .settingsLaunchAtLogin: "Avvia all'accesso",
        .settingsLanguage: "Lingua",
        .autoRefreshSeconds30: "30 secondi",
        .autoRefreshMinute1: "1 minuto",
        .autoRefreshMinutes5: "5 minuti",
        .autoRefreshMinutes15: "15 minuti",
        .autoRefreshDisabled: "Disattiva aggiornamento automatico",
        .totalModelUsage: "Uso per modello",
        .totalEmptyModels: "Nessun dato modello",
        .statusLoadingUsage: "Caricamento dati di utilizzo...",
        .statusNeedsHomeAuthorization: "Autorizza prima l'accesso alla cartella home in Impostazioni",
        .statusTotalNoTokenData: "Nessun dato token totale",
        .statusPartialLoading: "Alcuni dati sono ancora in caricamento",
        .chartTokenUsage: "Utilizzo token",
        .chartCost: "Costo",
        .shareTool: "Quota strumento",
        .shareModel: "Quota modello",
        .shareEmpty: "Nessun dato",
        .shareOther: "Altro",
        .recentDetailsTitle: "Dettagli recenti",
        .recentDetailsEmpty: "Nessun dettaglio sessione per il filtro corrente",
        .recentDetailsTime: "Ora",
        .recentDetailsSession: "Sessione",
        .recentDetailsTool: "Strumento",
        .recentDetailsProject: "Progetto",
        .recentDetailsModel: "Modello",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "Costo",
        .recentDetailsRecords: "Record",
        .periodNoTokenDataSuffix: "non ha dati token",
        .statusMenuOpen: "Apri TokenWatch",
        .refreshNow: "Aggiorna ora",
        .statusMenuQuit: "Esci da TokenWatch",
        .mainMenuAbout: "Informazioni su TokenWatch",
        .privacyPolicy: "Informativa sulla privacy",
        .mainMenuSettings: "Impostazioni...",
        .mainMenuHide: "Nascondi TokenWatch",
        .mainMenuHideOthers: "Nascondi altri",
        .mainMenuShowAll: "Mostra tutto",
        .mainMenuWindow: "Finestra",
        .mainMenuMinimize: "Contrai",
        .mainMenuZoom: "Zoom",
        .mainMenuBringAllToFront: "Porta tutto in primo piano",
        .refreshInProgress: "Aggiornamento",
        .refreshTotalAccessibility: "Aggiorna dati totali",
        .refreshUsageAccessibility: "Aggiorna dati di utilizzo",
        .refreshTodayAccessibility: "Aggiorna utilizzo token di oggi",
        .refreshingTotalAccessibility: "Aggiornamento dati totali",
        .refreshingUsageAccessibility: "Aggiornamento dati di utilizzo",
        .refreshingTodayAccessibility: "Aggiornamento utilizzo token di oggi",
        .popoverMonth: "Mese",
        .popoverWeek: "Settimana",
        .popoverToday: "Oggi",
        .popoverDailyAverage: "Media giornaliera",
        .popoverNoTodayTokens: "Nessun utilizzo token oggi",
        .popoverLowTodayTokens: "L'utilizzo token di oggi è leggero",
        .popoverMediumTodayTokens: "L'utilizzo token di oggi sta aumentando",
        .popoverHighTodayTokens: "L'utilizzo token di oggi è alto",
        .popoverVeryHighTodayTokens: "L'utilizzo token di oggi è molto alto",
        .popoverExtremeTodayTokens: "L'utilizzo token di oggi è fuori scala",
        .heatmapRecent22Weeks: "Ultime 22 settimane",
        .chartTokenAccessibility: "Grafico a barre dei token degli ultimi 12 mesi",
        .chartCostAccessibility: "Grafico a barre dei costi degli ultimi 12 mesi",
        .chartTokenAccessibilitySuffix: "grafico a barre dei token",
        .chartCostAccessibilitySuffix: "grafico a barre dei costi",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch vuole accedere alla cartella home",
        .authorizeAccessPrompt: "Autorizza",
        .errorCannotAccessHome: "Impossibile accedere alla cartella home. Autorizza di nuovo",
        .errorLoadFailedPrefix: "Caricamento dati non riuscito",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db non trovato: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "Impossibile aprire opencode.db (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "Query di opencode.db non riuscita (SQLite code=%d): %@",
    ]

    private static let nl: [AppStringKey: String] = [
        .languageSystem: "Systeem",
        .languageChinese: "Vereenvoudigd Chinees",
        .languageEnglish: "Engels",
        .appTagline: "Lokale AI-gebruiksmonitor",
        .sidebarTotal: "Totaal",
        .sidebarRecent12Months: "Afgelopen 12 maanden",
        .sidebarRecent7Days: "Afgelopen 7 dagen",
        .sidebarRecent30Days: "Afgelopen 30 dagen",
        .sidebarToday: "Vandaag",
        .sidebarSettings: "Instellingen",
        .dashboardOverviewNavigation: "Overzicht",
        .dashboardSessionsNavigation: "Sessies",
        .dashboardOverviewTitle: "Gebruiksoverzicht",
        .dashboardOverviewSubtitle: "Vat lokale records samen uit Claude Code, Codex rollout en opencode SQLite",
        .dashboardSessionsTitle: "Sessies",
        .dashboardSessionsSubtitle: "Bekijk sessie-aggregaten, kosten en gebruiksrecords op recente activiteit",
        .dashboardDataSources: "Gegevensbronnen",
        .dashboardLastLocalScan: "Laatste lokale scan",
        .dashboardMetricTotalTokens: "Totale tokens",
        .dashboardMetricTotalCost: "Totale kosten",
        .dashboardMetricSessions: "Sessies",
        .dashboardMetricRecords: "Records",
        .dashboardTrendTitle: "Trend",
        .dashboardTrendSubtitle: "Toont wijzigingen in tokengebruik en kosten",
        .dashboardTrendTokenLegend: "Tokengebruik",
        .dashboardModelRankTitle: "Modelgebruik ranking",
        .dashboardSourceShareTitle: "Brondeling",
        .dashboardProjectUsageTitle: "Projectgebruik",
        .dashboardNoProjectData: "Geen projectgegevens",
        .dashboardRangeDay: "Dag",
        .dashboardRange7Days: "7 dagen",
        .dashboardRange30Days: "30 dagen",
        .dashboardRangeAll: "Alles",
        .dashboardTotalSourcesProjectsFormat: "%d bronnen, %d projecten",
        .dashboardScanUpdating: "Lokale records worden bijgewerkt. Er wordt geen netwerk-API gebruikt.",
        .dashboardScanPending: "De lokale scan is nog niet voltooid. Er wordt geen netwerk-API gebruikt.",
        .dashboardScanUpdatedFormat: "%@ bijgewerkt. Er wordt geen netwerk-API gebruikt.",
        .dashboardJustNow: "Zojuist",
        .dashboardMinutesAgoFormat: "%d min geleden",
        .dashboardHoursAgoFormat: "%d uur geleden",
        .dashboardUnauthorized: "Niet geautoriseerd",
        .dashboardPreviousPage: "Vorige",
        .dashboardNextPage: "Volgende",
        .dashboardShowingSessionsFormat: "%@-%@ van %@ sessies",
        .dashboardLatestTime: "Laatste activiteit ↓",
        .dashboardSessionID: "Sessie-ID",
        .dashboardPrimaryModel: "Primair model",
        .dashboardNoSessions: "Geen sessies",
        .dashboardCopySessionIDAccessibility: "Volledige sessie-ID kopiëren",
        .dashboardCopyIDAccessibilityDescription: "Volledige ID kopiëren",
        .dashboardInput: "Invoer",
        .dashboardOutput: "Uitvoer",
        .dashboardCache: "Cache",
        .dashboardReasoning: "Redenering",
        .dashboardSessionsEmptyToday: "Vandaag geen sessierecords",
        .settingsTitle: "Instellingen",
        .settingsDescription: "Beheer algemene toegangsrechten en gegevensverversing voor TokenWatch.",
        .settingsAuthorizationTitle: "Algemene toegang",
        .settingsAuthorizeDirectory: "Thuismap autoriseren",
        .settingsAuthorized: "Geautoriseerd",
        .settingsAuthorize: "Autoriseren",
        .settingsRefreshAllData: "Alle gegevens verversen",
        .settingsAutoRefreshInterval: "Interval voor automatisch verversen",
        .settingsLaunchAtLogin: "Start bij inloggen",
        .settingsLanguage: "Taal",
        .autoRefreshSeconds30: "30 seconden",
        .autoRefreshMinute1: "1 minuut",
        .autoRefreshMinutes5: "5 minuten",
        .autoRefreshMinutes15: "15 minuten",
        .autoRefreshDisabled: "Automatisch verversen uitschakelen",
        .totalModelUsage: "Modelgebruik",
        .totalEmptyModels: "Geen modelgegevens",
        .statusLoadingUsage: "Gebruiksgegevens laden...",
        .statusNeedsHomeAuthorization: "Autoriseer eerst toegang tot de thuismap in Instellingen",
        .statusTotalNoTokenData: "Geen totale tokengegevens",
        .statusPartialLoading: "Sommige gegevens worden nog geladen",
        .chartTokenUsage: "Tokengebruik",
        .chartCost: "Kosten",
        .shareTool: "Toolaandeel",
        .shareModel: "Modelaandeel",
        .shareEmpty: "Geen gegevens",
        .shareOther: "Overig",
        .recentDetailsTitle: "Recente details",
        .recentDetailsEmpty: "Geen sessiedetails voor het huidige filter",
        .recentDetailsTime: "Tijd",
        .recentDetailsSession: "Sessie",
        .recentDetailsTool: "Tool",
        .recentDetailsProject: "Project",
        .recentDetailsModel: "Model",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "Kosten",
        .recentDetailsRecords: "Records",
        .periodNoTokenDataSuffix: "heeft geen tokengegevens",
        .statusMenuOpen: "TokenWatch openen",
        .refreshNow: "Nu verversen",
        .statusMenuQuit: "TokenWatch stoppen",
        .mainMenuAbout: "Over TokenWatch",
        .privacyPolicy: "Privacybeleid",
        .mainMenuSettings: "Instellingen...",
        .mainMenuHide: "Verberg TokenWatch",
        .mainMenuHideOthers: "Verberg andere",
        .mainMenuShowAll: "Toon alles",
        .mainMenuWindow: "Venster",
        .mainMenuMinimize: "Minimaliseer",
        .mainMenuZoom: "Zoom",
        .mainMenuBringAllToFront: "Breng alles naar voren",
        .refreshInProgress: "Verversen",
        .refreshTotalAccessibility: "Totale gegevens verversen",
        .refreshUsageAccessibility: "Gebruiksgegevens verversen",
        .refreshTodayAccessibility: "Tokengebruik van vandaag verversen",
        .refreshingTotalAccessibility: "Totale gegevens worden ververst",
        .refreshingUsageAccessibility: "Gebruiksgegevens worden ververst",
        .refreshingTodayAccessibility: "Tokengebruik van vandaag wordt ververst",
        .popoverMonth: "Maand",
        .popoverWeek: "Week",
        .popoverToday: "Vandaag",
        .popoverDailyAverage: "Dagelijks gem.",
        .popoverNoTodayTokens: "Vandaag geen tokengebruik",
        .popoverLowTodayTokens: "Het tokengebruik van vandaag is laag",
        .popoverMediumTodayTokens: "Het tokengebruik van vandaag neemt toe",
        .popoverHighTodayTokens: "Het tokengebruik van vandaag is hoog",
        .popoverVeryHighTodayTokens: "Het tokengebruik van vandaag is erg hoog",
        .popoverExtremeTodayTokens: "Het tokengebruik van vandaag is extreem hoog",
        .heatmapRecent22Weeks: "Afgelopen 22 weken",
        .chartTokenAccessibility: "Staafdiagram met tokens van de afgelopen 12 maanden",
        .chartCostAccessibility: "Staafdiagram met kosten van de afgelopen 12 maanden",
        .chartTokenAccessibilitySuffix: "staafdiagram met tokens",
        .chartCostAccessibilitySuffix: "staafdiagram met kosten",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch wil toegang tot je thuismap",
        .authorizeAccessPrompt: "Autoriseren",
        .errorCannotAccessHome: "Kan de thuismap niet openen. Autoriseer opnieuw",
        .errorLoadFailedPrefix: "Gegevens laden mislukt",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db niet gevonden: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "Kan opencode.db niet openen (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "Query op opencode.db mislukt (SQLite code=%d): %@",
    ]

    private static let pl: [AppStringKey: String] = [
        .languageSystem: "System",
        .languageChinese: "Chiński uproszczony",
        .languageEnglish: "Angielski",
        .appTagline: "Lokalny monitor użycia AI",
        .sidebarTotal: "Razem",
        .sidebarRecent12Months: "Ostatnie 12 miesięcy",
        .sidebarRecent7Days: "Ostatnie 7 dni",
        .sidebarRecent30Days: "Ostatnie 30 dni",
        .sidebarToday: "Dzisiaj",
        .sidebarSettings: "Ustawienia",
        .dashboardOverviewNavigation: "Przegląd",
        .dashboardSessionsNavigation: "Sesje",
        .dashboardOverviewTitle: "Przegląd użycia",
        .dashboardOverviewSubtitle: "Podsumowuje lokalne rekordy z Claude Code, Codex rollout i opencode SQLite",
        .dashboardSessionsTitle: "Sesje",
        .dashboardSessionsSubtitle: "Wyświetl agregaty sesji, koszty i rekordy użycia według ostatniej aktywności",
        .dashboardDataSources: "Źródła danych",
        .dashboardLastLocalScan: "Ostatni lokalny skan",
        .dashboardMetricTotalTokens: "Łączne tokeny",
        .dashboardMetricTotalCost: "Łączny koszt",
        .dashboardMetricSessions: "Sesje",
        .dashboardMetricRecords: "Rekordy",
        .dashboardTrendTitle: "Trend",
        .dashboardTrendSubtitle: "Pokazuje zmiany użycia tokenów i kosztu",
        .dashboardTrendTokenLegend: "Użycie tokenów",
        .dashboardModelRankTitle: "Ranking użycia modeli",
        .dashboardSourceShareTitle: "Udział źródeł",
        .dashboardProjectUsageTitle: "Użycie projektu",
        .dashboardNoProjectData: "Brak danych projektu",
        .dashboardRangeDay: "Dzień",
        .dashboardRange7Days: "7 dni",
        .dashboardRange30Days: "30 dni",
        .dashboardRangeAll: "Wszystko",
        .dashboardTotalSourcesProjectsFormat: "%d źródła, %d projekty",
        .dashboardScanUpdating: "Aktualizowanie lokalnych rekordów. Nie używa żadnego API sieciowego.",
        .dashboardScanPending: "Lokalny skan nie został jeszcze ukończony. Nie używa żadnego API sieciowego.",
        .dashboardScanUpdatedFormat: "Zaktualizowano %@. Nie używa żadnego API sieciowego.",
        .dashboardJustNow: "Przed chwilą",
        .dashboardMinutesAgoFormat: "%d min temu",
        .dashboardHoursAgoFormat: "%d godz. temu",
        .dashboardUnauthorized: "Nieautoryzowane",
        .dashboardPreviousPage: "Poprzednia",
        .dashboardNextPage: "Następna",
        .dashboardShowingSessionsFormat: "Pokazano %@-%@ z %@ sesji",
        .dashboardLatestTime: "Ostatnia aktywność ↓",
        .dashboardSessionID: "ID sesji",
        .dashboardPrimaryModel: "Model główny",
        .dashboardNoSessions: "Brak sesji",
        .dashboardCopySessionIDAccessibility: "Kopiuj pełne ID sesji",
        .dashboardCopyIDAccessibilityDescription: "Kopiuj pełne ID",
        .dashboardInput: "Wejście",
        .dashboardOutput: "Wyjście",
        .dashboardCache: "Pamięć cache",
        .dashboardReasoning: "Rozumowanie",
        .dashboardSessionsEmptyToday: "Brak rekordów sesji dzisiaj",
        .settingsTitle: "Ustawienia",
        .settingsDescription: "Zarządzaj ogólnymi uprawnieniami dostępu i odświeżaniem danych TokenWatch.",
        .settingsAuthorizationTitle: "Dostęp ogólny",
        .settingsAuthorizeDirectory: "Autoryzuj folder domowy",
        .settingsAuthorized: "Autoryzowano",
        .settingsAuthorize: "Autoryzuj",
        .settingsRefreshAllData: "Odśwież wszystkie dane",
        .settingsAutoRefreshInterval: "Interwał auto odświeżania",
        .settingsLaunchAtLogin: "Uruchamiaj przy logowaniu",
        .settingsLanguage: "Język",
        .autoRefreshSeconds30: "30 sekund",
        .autoRefreshMinute1: "1 minuta",
        .autoRefreshMinutes5: "5 minut",
        .autoRefreshMinutes15: "15 minut",
        .autoRefreshDisabled: "Wyłącz auto odświeżanie",
        .totalModelUsage: "Użycie modeli",
        .totalEmptyModels: "Brak danych modeli",
        .statusLoadingUsage: "Ładowanie danych użycia...",
        .statusNeedsHomeAuthorization: "Najpierw autoryzuj dostęp do folderu domowego w Ustawieniach",
        .statusTotalNoTokenData: "Brak łącznych danych tokenów",
        .statusPartialLoading: "Część danych nadal się ładuje",
        .chartTokenUsage: "Użycie tokenów",
        .chartCost: "Koszt",
        .shareTool: "Udział narzędzi",
        .shareModel: "Udział modeli",
        .shareEmpty: "Brak danych",
        .shareOther: "Inne",
        .recentDetailsTitle: "Ostatnie szczegóły",
        .recentDetailsEmpty: "Brak szczegółów sesji dla bieżącego filtra",
        .recentDetailsTime: "Czas",
        .recentDetailsSession: "Sesja",
        .recentDetailsTool: "Narzędzie",
        .recentDetailsProject: "Projekt",
        .recentDetailsModel: "Model",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "Koszt",
        .recentDetailsRecords: "Rekordy",
        .periodNoTokenDataSuffix: "nie ma danych tokenów",
        .statusMenuOpen: "Otwórz TokenWatch",
        .refreshNow: "Odśwież teraz",
        .statusMenuQuit: "Zamknij TokenWatch",
        .mainMenuAbout: "O TokenWatch",
        .privacyPolicy: "Polityka prywatności",
        .mainMenuSettings: "Ustawienia...",
        .mainMenuHide: "Ukryj TokenWatch",
        .mainMenuHideOthers: "Ukryj inne",
        .mainMenuShowAll: "Pokaż wszystko",
        .mainMenuWindow: "Okno",
        .mainMenuMinimize: "Minimalizuj",
        .mainMenuZoom: "Powiększ",
        .mainMenuBringAllToFront: "Przenieś wszystko na wierzch",
        .refreshInProgress: "Odświeżanie",
        .refreshTotalAccessibility: "Odśwież dane łączne",
        .refreshUsageAccessibility: "Odśwież dane użycia",
        .refreshTodayAccessibility: "Odśwież dzisiejsze użycie tokenów",
        .refreshingTotalAccessibility: "Odświeżanie danych łącznych",
        .refreshingUsageAccessibility: "Odświeżanie danych użycia",
        .refreshingTodayAccessibility: "Odświeżanie dzisiejszego użycia tokenów",
        .popoverMonth: "Miesiąc",
        .popoverWeek: "Tydzień",
        .popoverToday: "Dzisiaj",
        .popoverDailyAverage: "Śr. dzienna",
        .popoverNoTodayTokens: "Dzisiaj brak użycia tokenów",
        .popoverLowTodayTokens: "Dzisiejsze użycie tokenów jest niskie",
        .popoverMediumTodayTokens: "Dzisiejsze użycie tokenów rośnie",
        .popoverHighTodayTokens: "Dzisiejsze użycie tokenów jest wysokie",
        .popoverVeryHighTodayTokens: "Dzisiejsze użycie tokenów jest bardzo wysokie",
        .popoverExtremeTodayTokens: "Dzisiejsze użycie tokenów jest ekstremalne",
        .heatmapRecent22Weeks: "Ostatnie 22 tygodnie",
        .chartTokenAccessibility: "Wykres słupkowy tokenów z ostatnich 12 miesięcy",
        .chartCostAccessibility: "Wykres słupkowy kosztów z ostatnich 12 miesięcy",
        .chartTokenAccessibilitySuffix: "wykres słupkowy tokenów",
        .chartCostAccessibilitySuffix: "wykres słupkowy kosztów",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch chce uzyskać dostęp do folderu domowego",
        .authorizeAccessPrompt: "Autoryzuj",
        .errorCannotAccessHome: "Nie można uzyskać dostępu do folderu domowego. Autoryzuj ponownie",
        .errorLoadFailedPrefix: "Nie udało się załadować danych",
        .errorOpenCodeDatabaseNotFoundFormat: "Nie znaleziono opencode.db: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "Nie można otworzyć opencode.db (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "Zapytanie opencode.db nie powiodło się (SQLite code=%d): %@",
    ]

    private static let en: [AppStringKey: String] = [
        .languageSystem: "System",
        .languageChinese: "Simplified Chinese",
        .languageEnglish: "English",
        .appTagline: "Local AI Usage Monitor",
        .sidebarTotal: "Total",
        .sidebarRecent12Months: "Last 12 Months",
        .sidebarRecent7Days: "Last 7 Days",
        .sidebarRecent30Days: "Last 30 Days",
        .sidebarToday: "Today",
        .sidebarSettings: "Settings",
        .dashboardOverviewNavigation: "Overview",
        .dashboardSessionsNavigation: "Sessions",
        .dashboardOverviewTitle: "Usage Overview",
        .dashboardOverviewSubtitle: "Summarizes local records from Claude Code, Codex rollout, and opencode SQLite",
        .dashboardSessionsTitle: "Sessions",
        .dashboardSessionsSubtitle: "Review session aggregates, costs, and usage records by recent activity",
        .dashboardDataSources: "Data Sources",
        .dashboardLastLocalScan: "Last Local Scan",
        .dashboardMetricTotalTokens: "Total Tokens",
        .dashboardMetricTotalCost: "Total Cost",
        .dashboardMetricSessions: "Sessions",
        .dashboardMetricRecords: "Records",
        .dashboardTrendTitle: "Trend",
        .dashboardTrendSubtitle: "Shows token usage and cost changes",
        .dashboardTrendTokenLegend: "Token Usage",
        .dashboardModelRankTitle: "Model Usage Ranking",
        .dashboardSourceShareTitle: "Source Share",
        .dashboardProjectUsageTitle: "Project Usage",
        .dashboardNoProjectData: "No project data",
        .dashboardRangeDay: "Day",
        .dashboardRange7Days: "7 Days",
        .dashboardRange30Days: "30 Days",
        .dashboardRangeAll: "All",
        .dashboardTotalSourcesProjectsFormat: "%d sources, %d projects",
        .dashboardScanUpdating: "Updating local records. No network API is used.",
        .dashboardScanPending: "Local scan has not completed yet. No network API is used.",
        .dashboardScanUpdatedFormat: "Updated %@. No network API is used.",
        .dashboardJustNow: "just now",
        .dashboardMinutesAgoFormat: "%d minutes ago",
        .dashboardHoursAgoFormat: "%d hours ago",
        .dashboardUnauthorized: "Unauthorized",
        .dashboardPreviousPage: "Previous",
        .dashboardNextPage: "Next",
        .dashboardShowingSessionsFormat: "Showing %@-%@ of %@ sessions",
        .dashboardLatestTime: "Latest Time ↓",
        .dashboardSessionID: "Session ID",
        .dashboardPrimaryModel: "Primary Model",
        .dashboardNoSessions: "No sessions",
        .dashboardCopySessionIDAccessibility: "Copy full session ID",
        .dashboardCopyIDAccessibilityDescription: "Copy full ID",
        .dashboardInput: "Input",
        .dashboardOutput: "Output",
        .dashboardCache: "Cache",
        .dashboardReasoning: "Reasoning",
        .dashboardSessionsEmptyToday: "No session records today",
        .settingsTitle: "Settings",
        .settingsDescription: "Manage TokenWatch access permissions and data refresh.",
        .settingsAuthorizationTitle: "General Access",
        .settingsAuthorizeDirectory: "Authorize Home Folder",
        .settingsAuthorized: "Authorized",
        .settingsAuthorize: "Authorize",
        .settingsRefreshAllData: "Refresh All Data",
        .settingsAutoRefreshInterval: "Auto Refresh Interval",
        .settingsLaunchAtLogin: "Launch at Login",
        .settingsLanguage: "Language",
        .autoRefreshSeconds30: "30 seconds",
        .autoRefreshMinute1: "1 minute",
        .autoRefreshMinutes5: "5 minutes",
        .autoRefreshMinutes15: "15 minutes",
        .autoRefreshDisabled: "Disable Auto Refresh",
        .totalModelUsage: "Model Usage",
        .totalEmptyModels: "No model data",
        .statusLoadingUsage: "Loading usage data...",
        .statusNeedsHomeAuthorization: "Authorize home folder access in Settings first",
        .statusTotalNoTokenData: "No total token data",
        .statusPartialLoading: "Some data is still loading",
        .chartTokenUsage: "Token Usage",
        .chartCost: "Cost",
        .shareTool: "Tool Share",
        .shareModel: "Model Share",
        .shareEmpty: "No data",
        .shareOther: "Other",
        .recentDetailsTitle: "Recent Details",
        .recentDetailsEmpty: "No recent session details",
        .recentDetailsTime: "Time",
        .recentDetailsSession: "Session",
        .recentDetailsTool: "Tool",
        .recentDetailsProject: "Project",
        .recentDetailsModel: "Model",
        .recentDetailsTokens: "Tokens",
        .recentDetailsCost: "Cost",
        .recentDetailsRecords: "Records",
        .periodNoTokenDataSuffix: "has no token data",
        .statusMenuOpen: "Open TokenWatch",
        .refreshNow: "Refresh Now",
        .statusMenuQuit: "Quit TokenWatch",
        .mainMenuAbout: "About TokenWatch",
        .privacyPolicy: "Privacy Policy",
        .mainMenuSettings: "Settings...",
        .mainMenuHide: "Hide TokenWatch",
        .mainMenuHideOthers: "Hide Others",
        .mainMenuShowAll: "Show All",
        .mainMenuWindow: "Window",
        .mainMenuMinimize: "Minimize",
        .mainMenuZoom: "Zoom",
        .mainMenuBringAllToFront: "Bring All to Front",
        .refreshInProgress: "Refreshing",
        .refreshTotalAccessibility: "Refresh total data",
        .refreshUsageAccessibility: "Refresh usage data",
        .refreshTodayAccessibility: "Refresh today's token usage",
        .refreshingTotalAccessibility: "Refreshing total data",
        .refreshingUsageAccessibility: "Refreshing usage data",
        .refreshingTodayAccessibility: "Refreshing today's token usage",
        .popoverMonth: "Month",
        .popoverWeek: "Week",
        .popoverToday: "Today",
        .popoverDailyAverage: "Daily Avg",
        .popoverNoTodayTokens: "No token usage today",
        .popoverLowTodayTokens: "Today's token usage is light",
        .popoverMediumTodayTokens: "Today's token usage is picking up",
        .popoverHighTodayTokens: "Today's token usage is high",
        .popoverVeryHighTodayTokens: "Today's token usage is running hot",
        .popoverExtremeTodayTokens: "Today's token usage is off the charts",
        .heatmapRecent22Weeks: "Last 22 Weeks",
        .chartTokenAccessibility: "Last 12 months token bar chart",
        .chartCostAccessibility: "Last 12 months cost bar chart",
        .chartTokenAccessibilitySuffix: "token bar chart",
        .chartCostAccessibilitySuffix: "cost bar chart",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch wants to access your home folder",
        .authorizeAccessPrompt: "Authorize",
        .errorCannotAccessHome: "Cannot access home folder. Please authorize again",
        .errorLoadFailedPrefix: "Data load failed",
        .errorOpenCodeDatabaseNotFoundFormat: "opencode.db not found: %@",
        .errorOpenCodeDatabaseOpenFailedFormat: "Could not open opencode.db (SQLite code=%d): %@",
        .errorOpenCodeDatabaseQueryFailedFormat: "Could not query opencode.db (SQLite code=%d): %@",
    ]

    private static let localizedTables: [AppLanguage: [AppStringKey: String]] = [
        .zhHans: zhHans,
        .zhHant: zhHant,
        .en: en,
        .ja: ja,
        .ko: ko,
        .es: es,
        .de: de,
        .fr: fr,
        .ptBR: ptBR,
        .it: it,
        .nl: nl,
        .pl: pl,
    ]
}
