import Foundation

enum AppStringKey: CaseIterable, Sendable {
    case languageSystem
    case languageChinese
    case languageEnglish
    case sidebarTotal
    case sidebarRecent12Months
    case sidebarRecent30Days
    case sidebarToday
    case sidebarSettings
    case settingsTitle
    case settingsDescription
    case settingsAuthorizationTitle
    case settingsAuthorizeDirectory
    case settingsAuthorized
    case settingsAuthorize
    case settingsRefreshAllData
    case settingsAutoRefreshInterval
    case settingsLanguage
    case autoRefreshSeconds30
    case autoRefreshMinute1
    case autoRefreshMinutes5
    case autoRefreshMinutes15
    case autoRefreshDisabled
    case totalModelUsage
    case totalEmptyModels
    case statusLoadingUsage
    case statusNeedsHomeAuthorization
    case statusTotalNoTokenData
    case statusPartialLoading
    case chartTokenUsage
    case chartCost
    case shareTool
    case shareModel
    case shareEmpty
    case shareOther
    case periodNoTokenDataSuffix
    case statusMenuOpen
    case refreshNow
    case statusMenuQuit
    case refreshInProgress
    case refreshTotalAccessibility
    case refreshUsageAccessibility
    case refreshTodayAccessibility
    case refreshingTotalAccessibility
    case refreshingUsageAccessibility
    case refreshingTodayAccessibility
    case popoverMonth
    case popoverWeek
    case popoverToday
    case popoverDailyAverage
    case popoverNoTodayTokens
    case popoverLowTodayTokens
    case popoverMediumTodayTokens
    case popoverHighTodayTokens
    case popoverVeryHighTodayTokens
    case popoverExtremeTodayTokens
    case heatmapRecent22Weeks
    case chartTokenAccessibility
    case chartCostAccessibility
    case chartTokenAccessibilitySuffix
    case chartCostAccessibilitySuffix
    case statusBarTokenUnit
    case homeAccessMessage
    case authorizeAccessPrompt
    case errorCannotAccessHome
    case errorLoadFailedPrefix
}

enum AppStrings {
    /// Returns localized text for a stable app string key.
    static func text(_ key: AppStringKey, language: AppLanguage) -> String {
        text(key, language: language, tables: localizedTables)
    }

    static func text(
        _ key: AppStringKey,
        language: AppLanguage,
        zhHans zhHansTable: [AppStringKey: String],
        en enTable: [AppStringKey: String]
    ) -> String {
        text(key, language: language, tables: [.zhHans: zhHansTable, .en: enTable])
    }

    private static func text(
        _ key: AppStringKey,
        language: AppLanguage,
        tables: [AppLanguage: [AppStringKey: String]]
    ) -> String {
        tables[language]?[key] ?? tables[.en]?[key] ?? String(describing: key)
    }

    private static let zhHans: [AppStringKey: String] = [
        .languageSystem: "跟随系统",
        .languageChinese: "简体中文",
        .languageEnglish: "English",
        .sidebarTotal: "总计",
        .sidebarRecent12Months: "最近 12 个月",
        .sidebarRecent30Days: "最近 30 天",
        .sidebarToday: "本日",
        .sidebarSettings: "设置",
        .settingsTitle: "设置",
        .settingsDescription: "管理 TokenWatch 的通用访问权限和数据刷新。",
        .settingsAuthorizationTitle: "通用访问权限",
        .settingsAuthorizeDirectory: "授权访问用户目录",
        .settingsAuthorized: "已授权",
        .settingsAuthorize: "去授权",
        .settingsRefreshAllData: "刷新全部数据",
        .settingsAutoRefreshInterval: "自动刷新间隔",
        .settingsLanguage: "语言",
        .autoRefreshSeconds30: "30 秒",
        .autoRefreshMinute1: "1 分钟",
        .autoRefreshMinutes5: "5 分钟",
        .autoRefreshMinutes15: "15 分钟",
        .autoRefreshDisabled: "关闭自动刷新",
        .totalModelUsage: "模型消耗",
        .totalEmptyModels: "暂无模型数据",
        .statusLoadingUsage: "正在加载用量数据...",
        .statusNeedsHomeAuthorization: "请先在设置中授权访问用户目录",
        .statusTotalNoTokenData: "总计暂无 token 数据",
        .statusPartialLoading: "部分数据仍在加载",
        .chartTokenUsage: "Token 用量",
        .chartCost: "费用",
        .shareTool: "工具占比",
        .shareModel: "模型占比",
        .shareEmpty: "暂无数据",
        .shareOther: "其他",
        .periodNoTokenDataSuffix: "暂无 token 数据",
        .statusMenuOpen: "打开 TokenWatch",
        .refreshNow: "立即刷新",
        .statusMenuQuit: "退出 TokenWatch",
        .refreshInProgress: "正在刷新",
        .refreshTotalAccessibility: "刷新总计数据",
        .refreshUsageAccessibility: "刷新用量数据",
        .refreshTodayAccessibility: "刷新本日 token 消耗",
        .refreshingTotalAccessibility: "正在刷新总计数据",
        .refreshingUsageAccessibility: "正在刷新用量数据",
        .refreshingTodayAccessibility: "正在刷新本日 token 消耗",
        .popoverMonth: "本月",
        .popoverWeek: "本周",
        .popoverToday: "今日",
        .popoverDailyAverage: "日均",
        .popoverNoTodayTokens: "本日还没有消耗 token 哦～",
        .popoverLowTodayTokens: "本日 token 消耗很克制～",
        .popoverMediumTodayTokens: "本日 token 消耗正在加速～",
        .popoverHighTodayTokens: "本日 token 消耗有点上头～",
        .popoverVeryHighTodayTokens: "本日 token 消耗火力全开～",
        .popoverExtremeTodayTokens: "本日 token 消耗爆表～",
        .heatmapRecent22Weeks: "最近 22 周",
        .chartTokenAccessibility: "最近 12 个月 token 柱状图",
        .chartCostAccessibility: "最近 12 个月费用柱状图",
        .chartTokenAccessibilitySuffix: "token 柱状图",
        .chartCostAccessibilitySuffix: "费用柱状图",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch 想访问用户目录",
        .authorizeAccessPrompt: "授权访问",
        .errorCannotAccessHome: "无法访问用户目录,请重新授权",
        .errorLoadFailedPrefix: "数据加载失败",
    ]

    private static let zhHant: [AppStringKey: String] = [
        .languageSystem: "跟隨系統",
        .languageChinese: "簡體中文",
        .languageEnglish: "English",
        .sidebarTotal: "總計",
        .sidebarRecent12Months: "最近 12 個月",
        .sidebarRecent30Days: "最近 30 天",
        .sidebarToday: "今日",
        .sidebarSettings: "設定",
        .settingsTitle: "設定",
        .settingsDescription: "管理 TokenWatch 的一般存取權限與資料重新整理。",
        .settingsAuthorizationTitle: "一般存取權限",
        .settingsAuthorizeDirectory: "授權存取使用者目錄",
        .settingsAuthorized: "已授權",
        .settingsAuthorize: "前往授權",
        .settingsRefreshAllData: "重新整理全部資料",
        .settingsAutoRefreshInterval: "自動重新整理間隔",
        .settingsLanguage: "語言",
        .autoRefreshSeconds30: "30 秒",
        .autoRefreshMinute1: "1 分鐘",
        .autoRefreshMinutes5: "5 分鐘",
        .autoRefreshMinutes15: "15 分鐘",
        .autoRefreshDisabled: "關閉自動重新整理",
        .totalModelUsage: "模型消耗",
        .totalEmptyModels: "暫無模型資料",
        .statusLoadingUsage: "正在載入用量資料...",
        .statusNeedsHomeAuthorization: "請先在設定中授權存取使用者目錄",
        .statusTotalNoTokenData: "總計暫無 token 資料",
        .statusPartialLoading: "部分資料仍在載入",
        .chartTokenUsage: "Token 用量",
        .chartCost: "費用",
        .shareTool: "工具占比",
        .shareModel: "模型占比",
        .shareEmpty: "暫無資料",
        .shareOther: "其他",
        .periodNoTokenDataSuffix: "暫無 token 資料",
        .statusMenuOpen: "開啟 TokenWatch",
        .refreshNow: "立即重新整理",
        .statusMenuQuit: "結束 TokenWatch",
        .refreshInProgress: "正在重新整理",
        .refreshTotalAccessibility: "重新整理總計資料",
        .refreshUsageAccessibility: "重新整理用量資料",
        .refreshTodayAccessibility: "重新整理今日 token 消耗",
        .refreshingTotalAccessibility: "正在重新整理總計資料",
        .refreshingUsageAccessibility: "正在重新整理用量資料",
        .refreshingTodayAccessibility: "正在重新整理今日 token 消耗",
        .popoverMonth: "本月",
        .popoverWeek: "本週",
        .popoverToday: "今日",
        .popoverDailyAverage: "日均",
        .popoverNoTodayTokens: "今日還沒有消耗 token",
        .popoverLowTodayTokens: "今日 token 消耗很克制",
        .popoverMediumTodayTokens: "今日 token 消耗正在加速",
        .popoverHighTodayTokens: "今日 token 消耗偏高",
        .popoverVeryHighTodayTokens: "今日 token 消耗火力全開",
        .popoverExtremeTodayTokens: "今日 token 消耗爆表",
        .heatmapRecent22Weeks: "最近 22 週",
        .chartTokenAccessibility: "最近 12 個月 token 長條圖",
        .chartCostAccessibility: "最近 12 個月費用長條圖",
        .chartTokenAccessibilitySuffix: "token 長條圖",
        .chartCostAccessibilitySuffix: "費用長條圖",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch 想存取使用者目錄",
        .authorizeAccessPrompt: "授權存取",
        .errorCannotAccessHome: "無法存取使用者目錄,請重新授權",
        .errorLoadFailedPrefix: "資料載入失敗",
    ]

    private static let ja: [AppStringKey: String] = [
        .languageSystem: "システムに従う",
        .languageChinese: "簡体字中国語",
        .languageEnglish: "英語",
        .sidebarTotal: "合計",
        .sidebarRecent12Months: "過去12か月",
        .sidebarRecent30Days: "過去30日",
        .sidebarToday: "今日",
        .sidebarSettings: "設定",
        .settingsTitle: "設定",
        .settingsDescription: "TokenWatch の一般アクセス権限とデータ更新を管理します。",
        .settingsAuthorizationTitle: "一般アクセス",
        .settingsAuthorizeDirectory: "ホームフォルダへのアクセスを許可",
        .settingsAuthorized: "許可済み",
        .settingsAuthorize: "許可",
        .settingsRefreshAllData: "すべてのデータを更新",
        .settingsAutoRefreshInterval: "自動更新間隔",
        .settingsLanguage: "言語",
        .autoRefreshSeconds30: "30秒",
        .autoRefreshMinute1: "1分",
        .autoRefreshMinutes5: "5分",
        .autoRefreshMinutes15: "15分",
        .autoRefreshDisabled: "自動更新を無効化",
        .totalModelUsage: "モデル使用量",
        .totalEmptyModels: "モデルデータなし",
        .statusLoadingUsage: "使用量データを読み込み中...",
        .statusNeedsHomeAuthorization: "先に設定でホームフォルダへのアクセスを許可してください",
        .statusTotalNoTokenData: "合計 token データなし",
        .statusPartialLoading: "一部のデータを読み込み中",
        .chartTokenUsage: "Token 使用量",
        .chartCost: "コスト",
        .shareTool: "ツール比率",
        .shareModel: "モデル比率",
        .shareEmpty: "データなし",
        .shareOther: "その他",
        .periodNoTokenDataSuffix: "token データなし",
        .statusMenuOpen: "TokenWatch を開く",
        .refreshNow: "今すぐ更新",
        .statusMenuQuit: "TokenWatch を終了",
        .refreshInProgress: "更新中",
        .refreshTotalAccessibility: "合計データを更新",
        .refreshUsageAccessibility: "使用量データを更新",
        .refreshTodayAccessibility: "今日の token 使用量を更新",
        .refreshingTotalAccessibility: "合計データを更新中",
        .refreshingUsageAccessibility: "使用量データを更新中",
        .refreshingTodayAccessibility: "今日の token 使用量を更新中",
        .popoverMonth: "今月",
        .popoverWeek: "今週",
        .popoverToday: "今日",
        .popoverDailyAverage: "日平均",
        .popoverNoTodayTokens: "今日の token 使用量はまだありません",
        .popoverLowTodayTokens: "今日の token 使用量は少なめです",
        .popoverMediumTodayTokens: "今日の token 使用量が増えています",
        .popoverHighTodayTokens: "今日の token 使用量は高めです",
        .popoverVeryHighTodayTokens: "今日の token 使用量はかなり高めです",
        .popoverExtremeTodayTokens: "今日の token 使用量は上限級です",
        .heatmapRecent22Weeks: "過去22週間",
        .chartTokenAccessibility: "過去12か月の token 棒グラフ",
        .chartCostAccessibility: "過去12か月のコスト棒グラフ",
        .chartTokenAccessibilitySuffix: "token 棒グラフ",
        .chartCostAccessibilitySuffix: "コスト棒グラフ",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch がホームフォルダへのアクセスを求めています",
        .authorizeAccessPrompt: "許可",
        .errorCannotAccessHome: "ホームフォルダにアクセスできません。再度許可してください",
        .errorLoadFailedPrefix: "データの読み込みに失敗しました",
    ]

    private static let ko: [AppStringKey: String] = [
        .languageSystem: "시스템 설정",
        .languageChinese: "중국어 간체",
        .languageEnglish: "영어",
        .sidebarTotal: "합계",
        .sidebarRecent12Months: "최근 12개월",
        .sidebarRecent30Days: "최근 30일",
        .sidebarToday: "오늘",
        .sidebarSettings: "설정",
        .settingsTitle: "설정",
        .settingsDescription: "TokenWatch의 일반 접근 권한과 데이터 새로고침을 관리합니다.",
        .settingsAuthorizationTitle: "일반 접근 권한",
        .settingsAuthorizeDirectory: "홈 폴더 접근 허용",
        .settingsAuthorized: "허용됨",
        .settingsAuthorize: "허용",
        .settingsRefreshAllData: "모든 데이터 새로고침",
        .settingsAutoRefreshInterval: "자동 새로고침 간격",
        .settingsLanguage: "언어",
        .autoRefreshSeconds30: "30초",
        .autoRefreshMinute1: "1분",
        .autoRefreshMinutes5: "5분",
        .autoRefreshMinutes15: "15분",
        .autoRefreshDisabled: "자동 새로고침 끄기",
        .totalModelUsage: "모델 사용량",
        .totalEmptyModels: "모델 데이터 없음",
        .statusLoadingUsage: "사용량 데이터를 불러오는 중...",
        .statusNeedsHomeAuthorization: "먼저 설정에서 홈 폴더 접근을 허용하세요",
        .statusTotalNoTokenData: "합계 token 데이터 없음",
        .statusPartialLoading: "일부 데이터를 아직 불러오는 중",
        .chartTokenUsage: "Token 사용량",
        .chartCost: "비용",
        .shareTool: "도구 비율",
        .shareModel: "모델 비율",
        .shareEmpty: "데이터 없음",
        .shareOther: "기타",
        .periodNoTokenDataSuffix: "token 데이터 없음",
        .statusMenuOpen: "TokenWatch 열기",
        .refreshNow: "지금 새로고침",
        .statusMenuQuit: "TokenWatch 종료",
        .refreshInProgress: "새로고침 중",
        .refreshTotalAccessibility: "합계 데이터 새로고침",
        .refreshUsageAccessibility: "사용량 데이터 새로고침",
        .refreshTodayAccessibility: "오늘 token 사용량 새로고침",
        .refreshingTotalAccessibility: "합계 데이터를 새로고침 중",
        .refreshingUsageAccessibility: "사용량 데이터를 새로고침 중",
        .refreshingTodayAccessibility: "오늘 token 사용량을 새로고침 중",
        .popoverMonth: "이번 달",
        .popoverWeek: "이번 주",
        .popoverToday: "오늘",
        .popoverDailyAverage: "일평균",
        .popoverNoTodayTokens: "오늘은 아직 token 사용량이 없습니다",
        .popoverLowTodayTokens: "오늘 token 사용량은 낮습니다",
        .popoverMediumTodayTokens: "오늘 token 사용량이 늘고 있습니다",
        .popoverHighTodayTokens: "오늘 token 사용량이 높습니다",
        .popoverVeryHighTodayTokens: "오늘 token 사용량이 매우 높습니다",
        .popoverExtremeTodayTokens: "오늘 token 사용량이 한계를 넘었습니다",
        .heatmapRecent22Weeks: "최근 22주",
        .chartTokenAccessibility: "최근 12개월 token 막대 차트",
        .chartCostAccessibility: "최근 12개월 비용 막대 차트",
        .chartTokenAccessibilitySuffix: "token 막대 차트",
        .chartCostAccessibilitySuffix: "비용 막대 차트",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch가 홈 폴더 접근을 요청합니다",
        .authorizeAccessPrompt: "허용",
        .errorCannotAccessHome: "홈 폴더에 접근할 수 없습니다. 다시 허용하세요",
        .errorLoadFailedPrefix: "데이터 불러오기 실패",
    ]

    private static let es: [AppStringKey: String] = [
        .languageSystem: "Sistema",
        .languageChinese: "Chino simplificado",
        .languageEnglish: "Inglés",
        .sidebarTotal: "Total",
        .sidebarRecent12Months: "Últimos 12 meses",
        .sidebarRecent30Days: "Últimos 30 días",
        .sidebarToday: "Hoy",
        .sidebarSettings: "Configuración",
        .settingsTitle: "Configuración",
        .settingsDescription: "Gestiona los permisos de acceso generales y la actualización de datos de TokenWatch.",
        .settingsAuthorizationTitle: "Acceso general",
        .settingsAuthorizeDirectory: "Autorizar carpeta de inicio",
        .settingsAuthorized: "Autorizado",
        .settingsAuthorize: "Autorizar",
        .settingsRefreshAllData: "Actualizar todos los datos",
        .settingsAutoRefreshInterval: "Intervalo de actualización automática",
        .settingsLanguage: "Idioma",
        .autoRefreshSeconds30: "30 segundos",
        .autoRefreshMinute1: "1 minuto",
        .autoRefreshMinutes5: "5 minutos",
        .autoRefreshMinutes15: "15 minutos",
        .autoRefreshDisabled: "Desactivar actualización automática",
        .totalModelUsage: "Uso por modelo",
        .totalEmptyModels: "Sin datos de modelos",
        .statusLoadingUsage: "Cargando datos de uso...",
        .statusNeedsHomeAuthorization: "Autoriza primero el acceso a la carpeta de inicio en Configuración",
        .statusTotalNoTokenData: "Sin datos totales de tokens",
        .statusPartialLoading: "Algunos datos aún se están cargando",
        .chartTokenUsage: "Uso de tokens",
        .chartCost: "Coste",
        .shareTool: "Uso por herramienta",
        .shareModel: "Uso por modelo",
        .shareEmpty: "Sin datos",
        .shareOther: "Otros",
        .periodNoTokenDataSuffix: "no tiene datos de tokens",
        .statusMenuOpen: "Abrir TokenWatch",
        .refreshNow: "Actualizar ahora",
        .statusMenuQuit: "Salir de TokenWatch",
        .refreshInProgress: "Actualizando",
        .refreshTotalAccessibility: "Actualizar datos totales",
        .refreshUsageAccessibility: "Actualizar datos de uso",
        .refreshTodayAccessibility: "Actualizar uso de tokens de hoy",
        .refreshingTotalAccessibility: "Actualizando datos totales",
        .refreshingUsageAccessibility: "Actualizando datos de uso",
        .refreshingTodayAccessibility: "Actualizando uso de tokens de hoy",
        .popoverMonth: "Mes",
        .popoverWeek: "Semana",
        .popoverToday: "Hoy",
        .popoverDailyAverage: "Prom. diario",
        .popoverNoTodayTokens: "Hoy no hay uso de tokens",
        .popoverLowTodayTokens: "El uso de tokens de hoy es bajo",
        .popoverMediumTodayTokens: "El uso de tokens de hoy está aumentando",
        .popoverHighTodayTokens: "El uso de tokens de hoy es alto",
        .popoverVeryHighTodayTokens: "El uso de tokens de hoy está muy alto",
        .popoverExtremeTodayTokens: "El uso de tokens de hoy está fuera de escala",
        .heatmapRecent22Weeks: "Últimas 22 semanas",
        .chartTokenAccessibility: "Gráfico de barras de tokens de los últimos 12 meses",
        .chartCostAccessibility: "Gráfico de barras de coste de los últimos 12 meses",
        .chartTokenAccessibilitySuffix: "gráfico de barras de tokens",
        .chartCostAccessibilitySuffix: "gráfico de barras de coste",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch quiere acceder a tu carpeta de inicio",
        .authorizeAccessPrompt: "Autorizar",
        .errorCannotAccessHome: "No se puede acceder a la carpeta de inicio. Autoriza de nuevo",
        .errorLoadFailedPrefix: "Error al cargar datos",
    ]

    private static let de: [AppStringKey: String] = [
        .languageSystem: "System",
        .languageChinese: "Vereinfachtes Chinesisch",
        .languageEnglish: "Englisch",
        .sidebarTotal: "Gesamt",
        .sidebarRecent12Months: "Letzte 12 Monate",
        .sidebarRecent30Days: "Letzte 30 Tage",
        .sidebarToday: "Heute",
        .sidebarSettings: "Einstellungen",
        .settingsTitle: "Einstellungen",
        .settingsDescription: "Verwalte allgemeine Zugriffsrechte und Datenaktualisierung für TokenWatch.",
        .settingsAuthorizationTitle: "Allgemeiner Zugriff",
        .settingsAuthorizeDirectory: "Home-Ordner autorisieren",
        .settingsAuthorized: "Autorisiert",
        .settingsAuthorize: "Autorisieren",
        .settingsRefreshAllData: "Alle Daten aktualisieren",
        .settingsAutoRefreshInterval: "Intervall für Auto-Aktualisierung",
        .settingsLanguage: "Sprache",
        .autoRefreshSeconds30: "30 Sekunden",
        .autoRefreshMinute1: "1 Minute",
        .autoRefreshMinutes5: "5 Minuten",
        .autoRefreshMinutes15: "15 Minuten",
        .autoRefreshDisabled: "Auto-Aktualisierung deaktivieren",
        .totalModelUsage: "Modellnutzung",
        .totalEmptyModels: "Keine Modelldaten",
        .statusLoadingUsage: "Nutzungsdaten werden geladen...",
        .statusNeedsHomeAuthorization: "Autorisiere zuerst den Home-Ordnerzugriff in den Einstellungen",
        .statusTotalNoTokenData: "Keine gesamten Token-Daten",
        .statusPartialLoading: "Einige Daten werden noch geladen",
        .chartTokenUsage: "Token-Nutzung",
        .chartCost: "Kosten",
        .shareTool: "Tool-Anteil",
        .shareModel: "Modell-Anteil",
        .shareEmpty: "Keine Daten",
        .shareOther: "Andere",
        .periodNoTokenDataSuffix: "hat keine Token-Daten",
        .statusMenuOpen: "TokenWatch öffnen",
        .refreshNow: "Jetzt aktualisieren",
        .statusMenuQuit: "TokenWatch beenden",
        .refreshInProgress: "Aktualisierung läuft",
        .refreshTotalAccessibility: "Gesamtdaten aktualisieren",
        .refreshUsageAccessibility: "Nutzungsdaten aktualisieren",
        .refreshTodayAccessibility: "Heutige Token-Nutzung aktualisieren",
        .refreshingTotalAccessibility: "Gesamtdaten werden aktualisiert",
        .refreshingUsageAccessibility: "Nutzungsdaten werden aktualisiert",
        .refreshingTodayAccessibility: "Heutige Token-Nutzung wird aktualisiert",
        .popoverMonth: "Monat",
        .popoverWeek: "Woche",
        .popoverToday: "Heute",
        .popoverDailyAverage: "Tagesdurchschnitt",
        .popoverNoTodayTokens: "Heute keine Token-Nutzung",
        .popoverLowTodayTokens: "Die heutige Token-Nutzung ist niedrig",
        .popoverMediumTodayTokens: "Die heutige Token-Nutzung nimmt zu",
        .popoverHighTodayTokens: "Die heutige Token-Nutzung ist hoch",
        .popoverVeryHighTodayTokens: "Die heutige Token-Nutzung ist sehr hoch",
        .popoverExtremeTodayTokens: "Die heutige Token-Nutzung ist am Anschlag",
        .heatmapRecent22Weeks: "Letzte 22 Wochen",
        .chartTokenAccessibility: "Token-Balkendiagramm der letzten 12 Monate",
        .chartCostAccessibility: "Kosten-Balkendiagramm der letzten 12 Monate",
        .chartTokenAccessibilitySuffix: "Token-Balkendiagramm",
        .chartCostAccessibilitySuffix: "Kosten-Balkendiagramm",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch möchte auf deinen Home-Ordner zugreifen",
        .authorizeAccessPrompt: "Autorisieren",
        .errorCannotAccessHome: "Home-Ordner kann nicht geöffnet werden. Bitte erneut autorisieren",
        .errorLoadFailedPrefix: "Daten konnten nicht geladen werden",
    ]

    private static let fr: [AppStringKey: String] = [
        .languageSystem: "Système",
        .languageChinese: "Chinois simplifié",
        .languageEnglish: "Anglais",
        .sidebarTotal: "Total",
        .sidebarRecent12Months: "12 derniers mois",
        .sidebarRecent30Days: "30 derniers jours",
        .sidebarToday: "Aujourd'hui",
        .sidebarSettings: "Paramètres",
        .settingsTitle: "Paramètres",
        .settingsDescription: "Gérez les autorisations d'accès générales et l'actualisation des données de TokenWatch.",
        .settingsAuthorizationTitle: "Accès général",
        .settingsAuthorizeDirectory: "Autoriser le dossier personnel",
        .settingsAuthorized: "Autorisé",
        .settingsAuthorize: "Autoriser",
        .settingsRefreshAllData: "Actualiser toutes les données",
        .settingsAutoRefreshInterval: "Intervalle d'actualisation auto",
        .settingsLanguage: "Langue",
        .autoRefreshSeconds30: "30 secondes",
        .autoRefreshMinute1: "1 minute",
        .autoRefreshMinutes5: "5 minutes",
        .autoRefreshMinutes15: "15 minutes",
        .autoRefreshDisabled: "Désactiver l'actualisation auto",
        .totalModelUsage: "Utilisation par modèle",
        .totalEmptyModels: "Aucune donnée de modèle",
        .statusLoadingUsage: "Chargement des données d'utilisation...",
        .statusNeedsHomeAuthorization: "Autorisez d'abord l'accès au dossier personnel dans Paramètres",
        .statusTotalNoTokenData: "Aucune donnée totale de tokens",
        .statusPartialLoading: "Certaines données sont encore en cours de chargement",
        .chartTokenUsage: "Utilisation des tokens",
        .chartCost: "Coût",
        .shareTool: "Part par outil",
        .shareModel: "Part par modèle",
        .shareEmpty: "Aucune donnée",
        .shareOther: "Autres",
        .periodNoTokenDataSuffix: "n'a aucune donnée de tokens",
        .statusMenuOpen: "Ouvrir TokenWatch",
        .refreshNow: "Actualiser maintenant",
        .statusMenuQuit: "Quitter TokenWatch",
        .refreshInProgress: "Actualisation",
        .refreshTotalAccessibility: "Actualiser les données totales",
        .refreshUsageAccessibility: "Actualiser les données d'utilisation",
        .refreshTodayAccessibility: "Actualiser l'utilisation des tokens d'aujourd'hui",
        .refreshingTotalAccessibility: "Actualisation des données totales",
        .refreshingUsageAccessibility: "Actualisation des données d'utilisation",
        .refreshingTodayAccessibility: "Actualisation de l'utilisation des tokens d'aujourd'hui",
        .popoverMonth: "Mois",
        .popoverWeek: "Semaine",
        .popoverToday: "Aujourd'hui",
        .popoverDailyAverage: "Moy. jour",
        .popoverNoTodayTokens: "Aucune utilisation de tokens aujourd'hui",
        .popoverLowTodayTokens: "L'utilisation des tokens d'aujourd'hui est faible",
        .popoverMediumTodayTokens: "L'utilisation des tokens d'aujourd'hui accélère",
        .popoverHighTodayTokens: "L'utilisation des tokens d'aujourd'hui est élevée",
        .popoverVeryHighTodayTokens: "L'utilisation des tokens d'aujourd'hui est très élevée",
        .popoverExtremeTodayTokens: "L'utilisation des tokens d'aujourd'hui explose",
        .heatmapRecent22Weeks: "22 dernières semaines",
        .chartTokenAccessibility: "Graphique à barres des tokens des 12 derniers mois",
        .chartCostAccessibility: "Graphique à barres des coûts des 12 derniers mois",
        .chartTokenAccessibilitySuffix: "graphique à barres des tokens",
        .chartCostAccessibilitySuffix: "graphique à barres des coûts",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch veut accéder à votre dossier personnel",
        .authorizeAccessPrompt: "Autoriser",
        .errorCannotAccessHome: "Impossible d'accéder au dossier personnel. Veuillez autoriser à nouveau",
        .errorLoadFailedPrefix: "Échec du chargement des données",
    ]

    private static let ptBR: [AppStringKey: String] = [
        .languageSystem: "Sistema",
        .languageChinese: "Chinês simplificado",
        .languageEnglish: "Inglês",
        .sidebarTotal: "Total",
        .sidebarRecent12Months: "Últimos 12 meses",
        .sidebarRecent30Days: "Últimos 30 dias",
        .sidebarToday: "Hoje",
        .sidebarSettings: "Configurações",
        .settingsTitle: "Configurações",
        .settingsDescription: "Gerencie permissões gerais de acesso e atualização de dados do TokenWatch.",
        .settingsAuthorizationTitle: "Acesso geral",
        .settingsAuthorizeDirectory: "Autorizar pasta inicial",
        .settingsAuthorized: "Autorizado",
        .settingsAuthorize: "Autorizar",
        .settingsRefreshAllData: "Atualizar todos os dados",
        .settingsAutoRefreshInterval: "Intervalo de atualização automática",
        .settingsLanguage: "Idioma",
        .autoRefreshSeconds30: "30 segundos",
        .autoRefreshMinute1: "1 minuto",
        .autoRefreshMinutes5: "5 minutos",
        .autoRefreshMinutes15: "15 minutos",
        .autoRefreshDisabled: "Desativar atualização automática",
        .totalModelUsage: "Uso por modelo",
        .totalEmptyModels: "Sem dados de modelos",
        .statusLoadingUsage: "Carregando dados de uso...",
        .statusNeedsHomeAuthorization: "Autorize primeiro o acesso à pasta inicial em Configurações",
        .statusTotalNoTokenData: "Sem dados totais de tokens",
        .statusPartialLoading: "Alguns dados ainda estão carregando",
        .chartTokenUsage: "Uso de tokens",
        .chartCost: "Custo",
        .shareTool: "Participação por ferramenta",
        .shareModel: "Participação por modelo",
        .shareEmpty: "Sem dados",
        .shareOther: "Outros",
        .periodNoTokenDataSuffix: "não tem dados de tokens",
        .statusMenuOpen: "Abrir TokenWatch",
        .refreshNow: "Atualizar agora",
        .statusMenuQuit: "Sair do TokenWatch",
        .refreshInProgress: "Atualizando",
        .refreshTotalAccessibility: "Atualizar dados totais",
        .refreshUsageAccessibility: "Atualizar dados de uso",
        .refreshTodayAccessibility: "Atualizar uso de tokens de hoje",
        .refreshingTotalAccessibility: "Atualizando dados totais",
        .refreshingUsageAccessibility: "Atualizando dados de uso",
        .refreshingTodayAccessibility: "Atualizando uso de tokens de hoje",
        .popoverMonth: "Mês",
        .popoverWeek: "Semana",
        .popoverToday: "Hoje",
        .popoverDailyAverage: "Média diária",
        .popoverNoTodayTokens: "Sem uso de tokens hoje",
        .popoverLowTodayTokens: "O uso de tokens de hoje está leve",
        .popoverMediumTodayTokens: "O uso de tokens de hoje está aumentando",
        .popoverHighTodayTokens: "O uso de tokens de hoje está alto",
        .popoverVeryHighTodayTokens: "O uso de tokens de hoje está muito alto",
        .popoverExtremeTodayTokens: "O uso de tokens de hoje passou do limite",
        .heatmapRecent22Weeks: "Últimas 22 semanas",
        .chartTokenAccessibility: "Gráfico de barras de tokens dos últimos 12 meses",
        .chartCostAccessibility: "Gráfico de barras de custos dos últimos 12 meses",
        .chartTokenAccessibilitySuffix: "gráfico de barras de tokens",
        .chartCostAccessibilitySuffix: "gráfico de barras de custos",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch quer acessar sua pasta inicial",
        .authorizeAccessPrompt: "Autorizar",
        .errorCannotAccessHome: "Não foi possível acessar a pasta inicial. Autorize novamente",
        .errorLoadFailedPrefix: "Falha ao carregar dados",
    ]

    private static let it: [AppStringKey: String] = [
        .languageSystem: "Sistema",
        .languageChinese: "Cinese semplificato",
        .languageEnglish: "Inglese",
        .sidebarTotal: "Totale",
        .sidebarRecent12Months: "Ultimi 12 mesi",
        .sidebarRecent30Days: "Ultimi 30 giorni",
        .sidebarToday: "Oggi",
        .sidebarSettings: "Impostazioni",
        .settingsTitle: "Impostazioni",
        .settingsDescription: "Gestisci le autorizzazioni generali di accesso e l'aggiornamento dei dati di TokenWatch.",
        .settingsAuthorizationTitle: "Accesso generale",
        .settingsAuthorizeDirectory: "Autorizza cartella home",
        .settingsAuthorized: "Autorizzato",
        .settingsAuthorize: "Autorizza",
        .settingsRefreshAllData: "Aggiorna tutti i dati",
        .settingsAutoRefreshInterval: "Intervallo di aggiornamento automatico",
        .settingsLanguage: "Lingua",
        .autoRefreshSeconds30: "30 secondi",
        .autoRefreshMinute1: "1 minuto",
        .autoRefreshMinutes5: "5 minuti",
        .autoRefreshMinutes15: "15 minuti",
        .autoRefreshDisabled: "Disattiva aggiornamento automatico",
        .totalModelUsage: "Uso per modello",
        .totalEmptyModels: "Nessun dato modello",
        .statusLoadingUsage: "Caricamento dati di utilizzo...",
        .statusNeedsHomeAuthorization: "Autorizza prima l'accesso alla cartella home in Impostazioni",
        .statusTotalNoTokenData: "Nessun dato token totale",
        .statusPartialLoading: "Alcuni dati sono ancora in caricamento",
        .chartTokenUsage: "Utilizzo token",
        .chartCost: "Costo",
        .shareTool: "Quota strumento",
        .shareModel: "Quota modello",
        .shareEmpty: "Nessun dato",
        .shareOther: "Altro",
        .periodNoTokenDataSuffix: "non ha dati token",
        .statusMenuOpen: "Apri TokenWatch",
        .refreshNow: "Aggiorna ora",
        .statusMenuQuit: "Esci da TokenWatch",
        .refreshInProgress: "Aggiornamento",
        .refreshTotalAccessibility: "Aggiorna dati totali",
        .refreshUsageAccessibility: "Aggiorna dati di utilizzo",
        .refreshTodayAccessibility: "Aggiorna utilizzo token di oggi",
        .refreshingTotalAccessibility: "Aggiornamento dati totali",
        .refreshingUsageAccessibility: "Aggiornamento dati di utilizzo",
        .refreshingTodayAccessibility: "Aggiornamento utilizzo token di oggi",
        .popoverMonth: "Mese",
        .popoverWeek: "Settimana",
        .popoverToday: "Oggi",
        .popoverDailyAverage: "Media giornaliera",
        .popoverNoTodayTokens: "Nessun utilizzo token oggi",
        .popoverLowTodayTokens: "L'utilizzo token di oggi è leggero",
        .popoverMediumTodayTokens: "L'utilizzo token di oggi sta aumentando",
        .popoverHighTodayTokens: "L'utilizzo token di oggi è alto",
        .popoverVeryHighTodayTokens: "L'utilizzo token di oggi è molto alto",
        .popoverExtremeTodayTokens: "L'utilizzo token di oggi è fuori scala",
        .heatmapRecent22Weeks: "Ultime 22 settimane",
        .chartTokenAccessibility: "Grafico a barre dei token degli ultimi 12 mesi",
        .chartCostAccessibility: "Grafico a barre dei costi degli ultimi 12 mesi",
        .chartTokenAccessibilitySuffix: "grafico a barre dei token",
        .chartCostAccessibilitySuffix: "grafico a barre dei costi",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch vuole accedere alla cartella home",
        .authorizeAccessPrompt: "Autorizza",
        .errorCannotAccessHome: "Impossibile accedere alla cartella home. Autorizza di nuovo",
        .errorLoadFailedPrefix: "Caricamento dati non riuscito",
    ]

    private static let nl: [AppStringKey: String] = [
        .languageSystem: "Systeem",
        .languageChinese: "Vereenvoudigd Chinees",
        .languageEnglish: "Engels",
        .sidebarTotal: "Totaal",
        .sidebarRecent12Months: "Afgelopen 12 maanden",
        .sidebarRecent30Days: "Afgelopen 30 dagen",
        .sidebarToday: "Vandaag",
        .sidebarSettings: "Instellingen",
        .settingsTitle: "Instellingen",
        .settingsDescription: "Beheer algemene toegangsrechten en gegevensverversing voor TokenWatch.",
        .settingsAuthorizationTitle: "Algemene toegang",
        .settingsAuthorizeDirectory: "Thuismap autoriseren",
        .settingsAuthorized: "Geautoriseerd",
        .settingsAuthorize: "Autoriseren",
        .settingsRefreshAllData: "Alle gegevens verversen",
        .settingsAutoRefreshInterval: "Interval voor automatisch verversen",
        .settingsLanguage: "Taal",
        .autoRefreshSeconds30: "30 seconden",
        .autoRefreshMinute1: "1 minuut",
        .autoRefreshMinutes5: "5 minuten",
        .autoRefreshMinutes15: "15 minuten",
        .autoRefreshDisabled: "Automatisch verversen uitschakelen",
        .totalModelUsage: "Modelgebruik",
        .totalEmptyModels: "Geen modelgegevens",
        .statusLoadingUsage: "Gebruiksgegevens laden...",
        .statusNeedsHomeAuthorization: "Autoriseer eerst toegang tot de thuismap in Instellingen",
        .statusTotalNoTokenData: "Geen totale tokengegevens",
        .statusPartialLoading: "Sommige gegevens worden nog geladen",
        .chartTokenUsage: "Tokengebruik",
        .chartCost: "Kosten",
        .shareTool: "Toolaandeel",
        .shareModel: "Modelaandeel",
        .shareEmpty: "Geen gegevens",
        .shareOther: "Overig",
        .periodNoTokenDataSuffix: "heeft geen tokengegevens",
        .statusMenuOpen: "TokenWatch openen",
        .refreshNow: "Nu verversen",
        .statusMenuQuit: "TokenWatch stoppen",
        .refreshInProgress: "Verversen",
        .refreshTotalAccessibility: "Totale gegevens verversen",
        .refreshUsageAccessibility: "Gebruiksgegevens verversen",
        .refreshTodayAccessibility: "Tokengebruik van vandaag verversen",
        .refreshingTotalAccessibility: "Totale gegevens worden ververst",
        .refreshingUsageAccessibility: "Gebruiksgegevens worden ververst",
        .refreshingTodayAccessibility: "Tokengebruik van vandaag wordt ververst",
        .popoverMonth: "Maand",
        .popoverWeek: "Week",
        .popoverToday: "Vandaag",
        .popoverDailyAverage: "Dagelijks gem.",
        .popoverNoTodayTokens: "Vandaag geen tokengebruik",
        .popoverLowTodayTokens: "Het tokengebruik van vandaag is laag",
        .popoverMediumTodayTokens: "Het tokengebruik van vandaag neemt toe",
        .popoverHighTodayTokens: "Het tokengebruik van vandaag is hoog",
        .popoverVeryHighTodayTokens: "Het tokengebruik van vandaag is erg hoog",
        .popoverExtremeTodayTokens: "Het tokengebruik van vandaag is extreem hoog",
        .heatmapRecent22Weeks: "Afgelopen 22 weken",
        .chartTokenAccessibility: "Staafdiagram met tokens van de afgelopen 12 maanden",
        .chartCostAccessibility: "Staafdiagram met kosten van de afgelopen 12 maanden",
        .chartTokenAccessibilitySuffix: "staafdiagram met tokens",
        .chartCostAccessibilitySuffix: "staafdiagram met kosten",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch wil toegang tot je thuismap",
        .authorizeAccessPrompt: "Autoriseren",
        .errorCannotAccessHome: "Kan de thuismap niet openen. Autoriseer opnieuw",
        .errorLoadFailedPrefix: "Gegevens laden mislukt",
    ]

    private static let pl: [AppStringKey: String] = [
        .languageSystem: "System",
        .languageChinese: "Chiński uproszczony",
        .languageEnglish: "Angielski",
        .sidebarTotal: "Razem",
        .sidebarRecent12Months: "Ostatnie 12 miesięcy",
        .sidebarRecent30Days: "Ostatnie 30 dni",
        .sidebarToday: "Dzisiaj",
        .sidebarSettings: "Ustawienia",
        .settingsTitle: "Ustawienia",
        .settingsDescription: "Zarządzaj ogólnymi uprawnieniami dostępu i odświeżaniem danych TokenWatch.",
        .settingsAuthorizationTitle: "Dostęp ogólny",
        .settingsAuthorizeDirectory: "Autoryzuj folder domowy",
        .settingsAuthorized: "Autoryzowano",
        .settingsAuthorize: "Autoryzuj",
        .settingsRefreshAllData: "Odśwież wszystkie dane",
        .settingsAutoRefreshInterval: "Interwał auto odświeżania",
        .settingsLanguage: "Język",
        .autoRefreshSeconds30: "30 sekund",
        .autoRefreshMinute1: "1 minuta",
        .autoRefreshMinutes5: "5 minut",
        .autoRefreshMinutes15: "15 minut",
        .autoRefreshDisabled: "Wyłącz auto odświeżanie",
        .totalModelUsage: "Użycie modeli",
        .totalEmptyModels: "Brak danych modeli",
        .statusLoadingUsage: "Ładowanie danych użycia...",
        .statusNeedsHomeAuthorization: "Najpierw autoryzuj dostęp do folderu domowego w Ustawieniach",
        .statusTotalNoTokenData: "Brak łącznych danych tokenów",
        .statusPartialLoading: "Część danych nadal się ładuje",
        .chartTokenUsage: "Użycie tokenów",
        .chartCost: "Koszt",
        .shareTool: "Udział narzędzi",
        .shareModel: "Udział modeli",
        .shareEmpty: "Brak danych",
        .shareOther: "Inne",
        .periodNoTokenDataSuffix: "nie ma danych tokenów",
        .statusMenuOpen: "Otwórz TokenWatch",
        .refreshNow: "Odśwież teraz",
        .statusMenuQuit: "Zamknij TokenWatch",
        .refreshInProgress: "Odświeżanie",
        .refreshTotalAccessibility: "Odśwież dane łączne",
        .refreshUsageAccessibility: "Odśwież dane użycia",
        .refreshTodayAccessibility: "Odśwież dzisiejsze użycie tokenów",
        .refreshingTotalAccessibility: "Odświeżanie danych łącznych",
        .refreshingUsageAccessibility: "Odświeżanie danych użycia",
        .refreshingTodayAccessibility: "Odświeżanie dzisiejszego użycia tokenów",
        .popoverMonth: "Miesiąc",
        .popoverWeek: "Tydzień",
        .popoverToday: "Dzisiaj",
        .popoverDailyAverage: "Śr. dzienna",
        .popoverNoTodayTokens: "Dzisiaj brak użycia tokenów",
        .popoverLowTodayTokens: "Dzisiejsze użycie tokenów jest niskie",
        .popoverMediumTodayTokens: "Dzisiejsze użycie tokenów rośnie",
        .popoverHighTodayTokens: "Dzisiejsze użycie tokenów jest wysokie",
        .popoverVeryHighTodayTokens: "Dzisiejsze użycie tokenów jest bardzo wysokie",
        .popoverExtremeTodayTokens: "Dzisiejsze użycie tokenów jest ekstremalne",
        .heatmapRecent22Weeks: "Ostatnie 22 tygodnie",
        .chartTokenAccessibility: "Wykres słupkowy tokenów z ostatnich 12 miesięcy",
        .chartCostAccessibility: "Wykres słupkowy kosztów z ostatnich 12 miesięcy",
        .chartTokenAccessibilitySuffix: "wykres słupkowy tokenów",
        .chartCostAccessibilitySuffix: "wykres słupkowy kosztów",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch chce uzyskać dostęp do folderu domowego",
        .authorizeAccessPrompt: "Autoryzuj",
        .errorCannotAccessHome: "Nie można uzyskać dostępu do folderu domowego. Autoryzuj ponownie",
        .errorLoadFailedPrefix: "Nie udało się załadować danych",
    ]

    private static let en: [AppStringKey: String] = [
        .languageSystem: "System",
        .languageChinese: "Simplified Chinese",
        .languageEnglish: "English",
        .sidebarTotal: "Total",
        .sidebarRecent12Months: "Last 12 Months",
        .sidebarRecent30Days: "Last 30 Days",
        .sidebarToday: "Today",
        .sidebarSettings: "Settings",
        .settingsTitle: "Settings",
        .settingsDescription: "Manage TokenWatch access permissions and data refresh.",
        .settingsAuthorizationTitle: "General Access",
        .settingsAuthorizeDirectory: "Authorize Home Folder",
        .settingsAuthorized: "Authorized",
        .settingsAuthorize: "Authorize",
        .settingsRefreshAllData: "Refresh All Data",
        .settingsAutoRefreshInterval: "Auto Refresh Interval",
        .settingsLanguage: "Language",
        .autoRefreshSeconds30: "30 seconds",
        .autoRefreshMinute1: "1 minute",
        .autoRefreshMinutes5: "5 minutes",
        .autoRefreshMinutes15: "15 minutes",
        .autoRefreshDisabled: "Disable Auto Refresh",
        .totalModelUsage: "Model Usage",
        .totalEmptyModels: "No model data",
        .statusLoadingUsage: "Loading usage data...",
        .statusNeedsHomeAuthorization: "Authorize home folder access in Settings first",
        .statusTotalNoTokenData: "No total token data",
        .statusPartialLoading: "Some data is still loading",
        .chartTokenUsage: "Token Usage",
        .chartCost: "Cost",
        .shareTool: "Tool Share",
        .shareModel: "Model Share",
        .shareEmpty: "No data",
        .shareOther: "Other",
        .periodNoTokenDataSuffix: "has no token data",
        .statusMenuOpen: "Open TokenWatch",
        .refreshNow: "Refresh Now",
        .statusMenuQuit: "Quit TokenWatch",
        .refreshInProgress: "Refreshing",
        .refreshTotalAccessibility: "Refresh total data",
        .refreshUsageAccessibility: "Refresh usage data",
        .refreshTodayAccessibility: "Refresh today's token usage",
        .refreshingTotalAccessibility: "Refreshing total data",
        .refreshingUsageAccessibility: "Refreshing usage data",
        .refreshingTodayAccessibility: "Refreshing today's token usage",
        .popoverMonth: "Month",
        .popoverWeek: "Week",
        .popoverToday: "Today",
        .popoverDailyAverage: "Daily Avg",
        .popoverNoTodayTokens: "No token usage today",
        .popoverLowTodayTokens: "Today's token usage is light",
        .popoverMediumTodayTokens: "Today's token usage is picking up",
        .popoverHighTodayTokens: "Today's token usage is high",
        .popoverVeryHighTodayTokens: "Today's token usage is running hot",
        .popoverExtremeTodayTokens: "Today's token usage is off the charts",
        .heatmapRecent22Weeks: "Last 22 Weeks",
        .chartTokenAccessibility: "Last 12 months token bar chart",
        .chartCostAccessibility: "Last 12 months cost bar chart",
        .chartTokenAccessibilitySuffix: "token bar chart",
        .chartCostAccessibilitySuffix: "cost bar chart",
        .statusBarTokenUnit: "Tokens",
        .homeAccessMessage: "TokenWatch wants to access your home folder",
        .authorizeAccessPrompt: "Authorize",
        .errorCannotAccessHome: "Cannot access home folder. Please authorize again",
        .errorLoadFailedPrefix: "Data load failed",
    ]

    private static let localizedTables: [AppLanguage: [AppStringKey: String]] = [
        .zhHans: zhHans,
        .zhHant: zhHant,
        .en: en,
        .ja: ja,
        .ko: ko,
        .es: es,
        .de: de,
        .fr: fr,
        .ptBR: ptBR,
        .it: it,
        .nl: nl,
        .pl: pl,
    ]
}
